## Python Programming 

Python : Python is high level dynamically interpreted and general purpose programming language. 

## Practice Questions :

Q 01.Division - always return quatient with decimal

In [1]:
a  = 10 / 2
print(a)

5.0


Q 02.Floor Division - Always return quatient without decimal

In [2]:
b = 100 // 7
print(b)

14


Q 03.Exponent - used to calculate the power of a variable.

In [3]:
c = 2 ** 10
print(c)

1024


Comparison Oprator:
Q 04.Equal to ( "==" ) - used to check value are equal or not


In [4]:
a = 10
b = 23
print(a == b)

False


Q 05.Not Equal to ( " != ") 

In [5]:
print(a != b)

True


Q 06.Greater than (" > ") 

In [6]:
print(a > b)

False


Q 07.Less than (" < ") 

In [7]:
print(a < b)

True


Q 08.Greater than Equal to (" >= ") 

In [8]:
print(a >= b)

False


Q 09.Less than Equal to (" <= ")

In [9]:
print(a <= b)

True


Q 10.Compare subject's marks.

In [10]:
maths =77
eng = 87
hindi = 88
print(maths >= 75 and eng >= 85 and hindi >= 88)

True


Q 11.Take a value and perform Multipilication , Division, Floor Division and Modolus.

In [11]:
a = 15
print(a * 10)
print(a / 2)
print(a // 2)
print(a % 2)

150
7.5
7
1


## Conditional Statment 
## if, ..if..else, ..if..elif..else.

if : Block executs when if condition is true.

if..else : 1st(if) block executes when it's condition is true otherwise else block executes.

if..elif..else : Check one and more condition's at a time , check condition's step by step if no one condition are true then execute's else block.

Q 12.Check number's are same using if .

In [18]:
a = 12
b = 12
if a == b:
    print("number are same")

number are same


Q 13.Check a number divisible by b number using if .. else.

In [21]:
a = 7
b = 10
if a // b:
    print("a is divisible by b")
else:
    print("a is not divisible by b")


a is not divisible by b


Q 14.Ask the user for temperature in celcius and suggest what to wear.

In [12]:
temp=int(input("Enter the temperature in celcius"))
if (temp <= 0 ):
    print("wear a heavy coat and gloves")
elif ( temp <= 10):
    print("wear a jackect")
elif (temp <= 20 ):
    print("wear a hoodie")
elif (temp <= 30 ):
    print("wear a T shirt")
else:
    print("stay cool and hydrated")
    

Enter the temperature in celcius 41


stay cool and hydrated


Q 15.Input of days a book is overdue.

In [14]:
day = int(input("PLEASE ENTER THE NO.OF OVERDUE DAY'S ="))
if (day == 0):
    print(" NO FINE APPLICABLE")
elif (day <= 5 ):
    print(" PLEASE PAY FINE 2 RS. PER DAY",day*2)
elif (day <= 10 ):
    print(" PLEASE PAY THE FINE 5 RS. PER DAY",day*5)
else:
    print("PLEASE PAY FINE 10 RS. PER DAY",day*10)
    

PLEASE ENTER THE NO.OF OVERDUE DAY'S = 3


 PLEASE PAY FINE 2 RS. PER DAY 6


Q 16.Input : hunger level (1 to 10 ) suggest pizza size.

In [15]:
pizza = int(input("Witch size pizza you want, please enter the size of pizza 1 to 10"))
if (pizza == 1 or pizza <=3) :
   print("YOU WANT SMALL SIZE PIZZA")
elif (pizza == 4 or pizza <= 7):
   print("YOU WANT MEDIUM SIZE PIZZA")
elif ( pizza == 8 or pizza <= 10):
   print("YOU WANT LARGE SIZE PIZZA")
else:
   print("PLEASE ENTER VALID SIZE")

Witch size pizza you want, please enter the size of pizza 1 to 10 5


YOU WANT MEDIUM SIZE PIZZA


Q 17.Input.animal name match sound.

In [16]:
s = input("WITCH ANIMAL SOUND YOU WANT, PLEASE ENTER THIS ANIMAL NAME")

if s == "dog":
    print("DOG DO BARK")
elif (s == "cat"):
    print("CAT DO MEOW")
elif (s == "cow"):
    print("COW DO MOO")
elif (s == "duck"):
    print("DUCK DO QUACK")
else:
    print("PLEASE ENTER VALID NAME")

WITCH ANIMAL SOUND YOU WANT, PLEASE ENTER THIS ANIMAL NAME dog


DOG DO BARK


Q 18.Write a program that checks if a number is prime (divisible only by 1 and itself).

In [23]:
num = int(input("ENTER ANY NUMBER ="))
if num <= 1:
    print("PRIME NUMBER STARTS FROM 2,PLEASE ENTER VALID VALUE")
elif num == 2 or num == 3 or num == 5 or num == 7:
    print("THIS IS A PRIME NUMBER")
elif num % 2 ==0:
    print("THIS IS NOT A PRIME NUMBER , ITS DIVISIBLE BY 2 ")
elif num % 3 ==0:
    print("THIS IS PRIME NUMBER , ITS DIVISIBLE BY 3")
elif num % 5 ==0:
    print("THIS IS NOT A PRIME NUMBER , ITS DIVISIBLE BY 5")
elif num % 7 ==0:
    print("THIS IS NOT A PRIME NUMBER , ITS DIVISIBLE BY 7")
else:
    print("THIS IS A PRIME NUMBER")

ENTER ANY NUMBER = 5


THIS IS A PRIME NUMBER


## Loops:

## For Loop :

For Loop : For loop are used for sequence/range,whenever we know the of iteration required then we can use For Loop.

## While Loop :

While Loop : While loop is used for condition's or when we don't know the number's of iteration's required.

Q 19.Print odd numbers between 1-20.

In [24]:
for i in range(1,21):
    if i % 2==1:
        print("ODD NUMBER =",i)

ODD NUMBER = 1
ODD NUMBER = 3
ODD NUMBER = 5
ODD NUMBER = 7
ODD NUMBER = 9
ODD NUMBER = 11
ODD NUMBER = 13
ODD NUMBER = 15
ODD NUMBER = 17
ODD NUMBER = 19


Q 20.Print the numbers divisible by 3 in between 1-30.

In [26]:
for i in range(1,31):
    if i % 3== 0:
        print("NUMBER IS DEVISIBLE BY 3 =",i)

NUMBER IS DEVISIBLE BY 3 = 3
NUMBER IS DEVISIBLE BY 3 = 6
NUMBER IS DEVISIBLE BY 3 = 9
NUMBER IS DEVISIBLE BY 3 = 12
NUMBER IS DEVISIBLE BY 3 = 15
NUMBER IS DEVISIBLE BY 3 = 18
NUMBER IS DEVISIBLE BY 3 = 21
NUMBER IS DEVISIBLE BY 3 = 24
NUMBER IS DEVISIBLE BY 3 = 27
NUMBER IS DEVISIBLE BY 3 = 30


Q 21.Ask the user for a number n and print the sum of numbers from 1 to n using a while loop.

In [27]:
num = int(input("ENTER ANY NUMBER"))
i = 1
total = 0
while i <= num:
      total += i
      i += 1
print("The sum of numbers from 1 to",num,"is",total) 

ENTER ANY NUMBER 12


The sum of numbers from 1 to 12 is 78


Q 22.Keep asking the user for input until they type "quit", then exit.

In [28]:
n = input("YOU WANT TO QUIT")

while n != "quit":
      n = input("ENTER AGAIN")
if n == "quit":
      print("SUCCESSFULLY QUIT ",n)

YOU WANT TO QUIT no
ENTER AGAIN no
ENTER AGAIN quit


SUCCESSFULLY QUIT  quit


Q 23.Ask the user to enter a starting number and count down to 0 using a while loop.

In [33]:
n = int(input("Enter number: "))
i = n
while i > 0:
    print(i)
    i -= 1

Enter number:  5


5
4
3
2
1


Q 24.Print powers of 2 (2, 4, 8, 16, …) using a while loop, until the result is greater than 1000.

In [34]:
i = 1
while 2 ** i <= 1000:
    print(2 ** i)
    i += 1

2
4
8
16
32
64
128
256
512


Q 25.Given a list of numbers,calculate the sum of all elements that are greater than 50 or divisible by 3, but not both.

In [37]:
l = [12, 13, 14, 15, 16, 17]

total = 0
for i in l:
    if i % 3 == 0:
        total += 1
        print(i)


12
15


Q 26.Take 5 numbers from user, add them to a list and for each odd number add +2 and even number substract -1

In [38]:
total = 0
count = 0
while count <= 4:
      a = int(input("enter 5 numbers"))
      count += 1
      if a % 2 == 0:
         a -= 1
         print(a)
      else:
          a += 2
          print(a)

enter 5 numbers 11


13


enter 5 numbers 25


27


enter 5 numbers 25


27


enter 5 numbers 2


1


enter 5 numbers 45


47


Q 27.Choose a secret number (e.g., 7). Ask the user to guess a number.
If their guess is too low, print "Too low!".
If their guess is too high, print "Too high!".
If their guess is correct, print "Congratulations! You guessed it!".

In [39]:
a = 991
b = int(input("guess a number"))
if a > b:
    print("Too low!")
elif a < b:
    print("Too hign!")
elif a == b:
    print("Congratulations! You guessed it!")

guess a number 5


Too low!


Q 28..Ask the user for a starting and ending number. Print all numbers in that range, except for multiples of 3.

In [40]:
s = int(input("enter starting number"))
e = int(input("enter ending number"))
for i in range(s,e):
    print(i)

enter starting number 4
enter ending number 8


4
5
6
7


Q 29.Write a program that asks the user to enter a password ("python123"). Allow them a maximum of 3 attempts. After each incorrect attempt, prompt them again. If they get it right within 3 attempts, print "Access Granted". Otherwise, print "Access Denied" after the failed attempts.

In [41]:
password = input("ENTER YOUR PASSWORD")
count = 1

while count <= 2:
   if (password == "python123"):
        print("ACCESS GRANTED")
        count = 2
    
      
        
   elif password != "python123" or count < 2  :
        print("INVALID PASSWORD")
        count +=1
        password = input("ENTER PASSWORD")
        
        
if password != "python123":
        print("ACCESS BLOCK")

ENTER YOUR PASSWORD fghj


INVALID PASSWORD


ENTER PASSWORD dfg


INVALID PASSWORD


ENTER PASSWORD python123


Q 30.Using nested loops, print the following pattern:
*
**
***
****
*****

In [42]:

for i in range(0,5):
    for n in range(i+1):
     print("*",end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


Q 31.Check the number's in list those are divisible by 4 & 6.

In [43]:
a = [12,14,34,35,25,22]
for i in a:
    if i % 4 == 0 and i % 6 == 0:
          print(i, "is divisible by 4 & 6")
    else:
        print(i,"is not divisible by 4 & 6")

12 is divisible by 4 & 6
14 is not divisible by 4 & 6
34 is not divisible by 4 & 6
35 is not divisible by 4 & 6
25 is not divisible by 4 & 6
22 is not divisible by 4 & 6


Q 32.Take the number from user and Print the first 5 multiples of the number.

In [44]:
i = int(input("ENTER A NUMBER ="))
c = i ** 5
print( "FRIST 5 MULTIPLICATION OF A NUMBER =",c)

ENTER A NUMBER = 12


FRIST 5 MULTIPLICATION OF A NUMBER = 248832


Q 33.Write a program to check if two numbers are equal without using the == operator.

In [45]:
a = int(input("ENTER 1 NUMBER ="))
b = int(input("ENTER 2 NUMBER ="))
if a >= b and b <= a:
    print ("numbers are equal =")
else:
    print("NUMBER'S ARE NOT EQUAL =",a,b)

ENTER 1 NUMBER = 5
ENTER 2 NUMBER = 47


NUMBER'S ARE NOT EQUAL = 5 47


Q 34.Given a year, check whether it's a leap year.Take the year from the user.

In [46]:
y = int(input("ENTER YEAR ="))

if y % 4 == 0 or y % 400 == 0 and y % 100 == 0:
    print("THIS IS A LEAP YEAR =",y)
else:
    print("THIS IS NOT LEAP YEAR =",y)

ENTER YEAR = 2025


THIS IS NOT LEAP YEAR = 2025


Q 35.Ask the user to input 10 numbers and count how many are:
Positive
Negative
Zero

In [51]:
a = [131,123,0,-35,-7]

sum = 0
for i in a:
    if i >= 0:
        total = sum + 1
        print("NUMBER  IS POSSITIVE =",i,total)

    if i <= 0:
        print("NUMBER IS NEGATIVE =",i)

    if i == 0:
        print("NUMBER IS ZERO =",i)

NUMBER  IS POSSITIVE = 131 1
NUMBER  IS POSSITIVE = 123 1
NUMBER  IS POSSITIVE = 0 1
NUMBER IS NEGATIVE = 0
NUMBER IS ZERO = 0
NUMBER IS NEGATIVE = -35
NUMBER IS NEGATIVE = -7


Q 36.Take a number n and print all odd numbers from n down to 1.

In [54]:
n = int(input("ENTER A NUMBER ="))

for n in range(n,1,-1):
    if n % 2 == 1:
        print(n)

ENTER A NUMBER = 5


5
3


Q 37.Take principal, rate, and time as input, and calculate simple interest.

In [55]:
p = float(input("ENTER THE AMOUNT ="))
r = float(input("ENTER THE RATE OF INTRESTE ="))
t = float(input("ENTER THE TIME IN YEAR ="))
print(":...............................:")
si = (p * r * t)/100
i = si - p

print("YOUR AMMOUNT IS =",p)
print("RATE OF INTREST =",r)
print("FOR YEAR'S =",t)
print("SIMPLE RATE OF INTREST ON YOUR AMOUNT = ",i)
print("TOTAL AMOUNT WITH INTREST =",si)

ENTER THE AMOUNT = 100005
ENTER THE RATE OF INTRESTE = 54
ENTER THE TIME IN YEAR = 5


:...............................:
YOUR AMMOUNT IS = 100005.0
RATE OF INTREST = 54.0
FOR YEAR'S = 5.0
SIMPLE RATE OF INTREST ON YOUR AMOUNT =  170008.5
TOTAL AMOUNT WITH INTREST = 270013.5


Q 38.Print numbers from 1 to 50:

If divisible by 3, print "Fizz"

If divisible by 5, print "Buzz"

If divisible by both, print "FizzBuzz"

In [56]:
for i in range(1,50):
    if i % 3 == 0 :
        print("Fizz",i)
    if i % 5 == 0 :
        print("Buzz",i)
    if i % 3 == 0 and i % 5 == 0 :
        print("FizzBuzz",i)

Fizz 3
Buzz 5
Fizz 6
Fizz 9
Buzz 10
Fizz 12
Fizz 15
Buzz 15
FizzBuzz 15
Fizz 18
Buzz 20
Fizz 21
Fizz 24
Buzz 25
Fizz 27
Fizz 30
Buzz 30
FizzBuzz 30
Fizz 33
Buzz 35
Fizz 36
Fizz 39
Buzz 40
Fizz 42
Fizz 45
Buzz 45
FizzBuzz 45
Fizz 48


Q 39. Take n, and compute the sum of squares: 1² + 2² + 3² + ... + n²

In [57]:
n = int(input("enter number ="))
sum_s = 0
for i in range(n):
    square = i * i
    sum_s += square
print(sum_s)

enter number = 5


30


Q 40.Take two integers and print both the quotient and the remainder.

In [58]:
a = int(input("ENTER 1 NUMBER ="))
b = int(input("ENTER 2 NUMBER ="))
c = a / b
d = a % b
print("QUOTIENT IS =",c)
print("REMAINDER IS =",d)

ENTER 1 NUMBER = 45
ENTER 2 NUMBER = 12


QUOTIENT IS = 3.75
REMAINDER IS = 9


Q 41.Take n, and calculate the sum of all numbers below n that are divisible by 3 or 5.

In [60]:
n = int(input("ENTER THE NUMBER ="))
sum = 0

for i in range(1,n):
    if i % 3 == 0 and i % 5 == 0:
         sum += i
print("SUM OF NUMBER'S THIS ARE DIVISIBLE BY 3 & 5 =",sum)

ENTER THE NUMBER = 4568


SUM OF NUMBER'S THIS ARE DIVISIBLE BY 3 & 5 = 695400


Q 42. Ask the user to enter a 2-digit number as a string (e.g., '45'). Convert each character to an integer and print their sum: 4 + 5 = 9.

In [61]:
a = input("enter 1 number")
b = input("enter 2 number")
j=int(a)
s=int(b)
c = j + s
print(c)

enter 1 number 20
enter 2 number 25


45


Q 43.Ask for a number n. Print the first n even numbers starting from 2.

In [63]:
n = int(input("enter number ="))

for n in range(2,n):
    if n % 2 == 0:
        print(n)

enter number = 10


2
4
6
8


Q 44.Ask for 3 numbers. Print the smallest (using only if/elif/else).

In [65]:
a = int(input("enter 1 number ="))
b = int(input("enter 2 number ="))
c = int(input("enter 3 number ="))
if a <= b and a <= c :
    print("a is smallest")
elif b <= a and b <= c :
    print("b is smallest")
elif c <= a and c <= b:
    print("c is smallest")

enter 1 number = 45
enter 2 number = 47
enter 3 number = 40


c is smallest


Q 45.Input length and width. Print the area and perimeter.

In [67]:
length = float(input("enter length ="))
weigth = float(input("enter weigth"))
c = (length + weigth)*2
print("are of perimeter",c)

enter length = 45
enter weigth 12


are of perimeter 114.0


Q 46.Ask for a number. Print the remainder when divided by 2, 3, 4, and 5.

In [68]:
n = int(input("enter number ="))

if n % 2 and n % 3 and n % 4 and n % 5:
    a = n % 2
    b = n % 3
    c = n % 4
    d = n % 5
print("remainder is =",a,"",b,"",c,"",d)

enter number = 45


remainder is = 45  47  114.0  9


Q 47.Ask for 3 digits separately (like 4, 7, 2). Combine them into the number 472.

In [69]:
a = input("enter 1 number =")
b = input("enter 2 number =")
c = input("enter 3 number =")
d = a + b + c
print(d)

enter 1 number = 45
enter 2 number = 25
enter 3 number = 22


452522


Q 48.Pizza Slice Divider
Input total slices and number of friends. Calculate:

How many slices each gets

  

In [70]:
s = int(input("ENTER THE NUMBER OF SLICE OF PIZZA ="))
f = int(input("ENTER THE NUBER OF FRIEND ="))

c = s % f
print("slice of each friends =",c)

ENTER THE NUMBER OF SLICE OF PIZZA = 4
ENTER THE NUBER OF FRIEND = 5


slice of each friends = 4


Q 49.Input a number. Print all numbers that divide it exactly (its factors).

Q 50.Ask for base and exponent. Calculate power using a loop.

In [71]:
b = int(input("ENTER BASE VALUE ="))
e = int(input("ENTER EXPONENT OF NUMBER ="))
c = b ** e
print("POWER OF THE NUMBERS =",c)

ENTER BASE VALUE = 50
ENTER EXPONENT OF NUMBER = 6


POWER OF THE NUMBERS = 15625000000


Q 51.Ask for a single digit (0–9). Print the digit in words (e.g., 5 → "Five").

In [73]:
d = int(input("ENTER THE NUMBER ="))
if d == 0:
    print("zero")
elif d == 1:
    print("one")
elif d == 2:
    print("two")
elif d == 3:
    print("three")
elif d == 4:
    print("four")
elif d== 5:
    print("five")
elif d == 6:
    print("six")
elif d == 7:
    print("seven")
elif d == 8:
    print("eight")
elif d == 9:
    print("nine")

ENTER THE NUMBER = 5


five


Q 52.Electricity Bill Calculator
Ask for units used. Calculate & Display bill:
First 100 units: ₹1.5/unit
Next 100: ₹2.5/unit 
Above 200: ₹4/unit

In [75]:
u = float(input("ENTER YOUR UNIT ="))

if u <= 100:
    print("PER UNIT CHARGE IS 1.5/UNIT ")
    print("TOTAL BILL =",u * 1.5)
elif u <= 200:
    print("PER UNIT CHARGE IS 2.5/UNIT ")
    print("TOTAL BILL =",u * 2.5)
elif u >= 200:
    print("PER UNIT CHARGE IS 4/UNIT ")
    print("TOTAL BILL =",u * 4)

ENTER YOUR UNIT = 5


PER UNIT CHARGE IS 1.5/UNIT 
TOTAL BILL = 7.5


Q 53.Ask for a number. If the last digit is 0, print "Ends with zero".

In [77]:
n = int(input("ENTER ANY NUMBER ="))
if n % 5 == 0 or n % 10 == 0:
    print("NUMBER END WITH ZERO =",n)
else:
    print("NUMBER IS NOT END WITH ZERO",n)

ENTER ANY NUMBER = 3


NUMBER IS NOT END WITH ZERO 3


Q 54.Input 4 numbers: a, b, c, d. Compare sum of a + b with c + d. Print which sum is greater.

In [78]:
a = int(input("ENTER 1 NUMBER ="))
b = int(input("ENTER 2 NUMBER ="))
c = int(input("ENTER 3 NUMBER ="))
d = int(input("ENTER 4 NUMBER ="))

e = a + b
f = c + d
if e > f:
    print("a + b SUM IS GREATER",e)
elif f > e:
    print("c + d SUM IS GREATER",f)

ENTER 1 NUMBER = 20
ENTER 2 NUMBER = 55
ENTER 3 NUMBER = 47
ENTER 4 NUMBER = 6


a + b SUM IS GREATER 75


Q 55. Check if Square of a Number is Even or Odd
* Input a number. Calculate its square. Say whether it's even or odd.

In [79]:
num = int(input("ENTER THE NUMBER ="))

s = num ** 2
if s % 2 == 0:
    print("THIS NUMBER SQUARE IS EVEN =",s)
elif s % 2 != 0:
    print("THIS NUMBER SQUARE IS ODD =",s)

ENTER THE NUMBER = 20


THIS NUMBER SQUARE IS EVEN = 400


Q 56.Print Reverse Table - Input a number. Print its table in reverse

In [80]:
n = int(input("enter number"))

for i in range(10,0,-1):
    print(i*n)

enter number 3


30
27
24
21
18
15
12
9
6
3


Q 57.Write a Python program that asks the user to enter a number between 1 and 100. Then the program should: 

In [83]:
a = int(input("enter number"))

if a % 2 == 0:
    print("number is even",a)
elif a % 2 != 0:
    print("number is odd =",a)
for a in range(2,a):
    if a % 2 == 0:
        print("number is even",a)
for a in range(1,a):
    if a % 2 != 0:
        print("number is odd",a)
if a <= 50:
    print("number is less than 50 =",a)
elif a >= 50:
    print("number is greater than 50",a)

enter number 10


number is even 10
number is even 2
number is even 4
number is even 6
number is even 8
number is odd 1
number is odd 3
number is odd 5
number is odd 7
number is less than 50 = 8


Q 58.Write a Python program to calculate the sum of all even numbers between 1 and a number entered by the user.

In [84]:
n = int(input("enter the number ="))
sum = 0

for i in range(1,n):
    if i % 2 == 0:
        sum += i
print("sum of all even number 1 to",n,"is =",i)

enter the number = 55


sum of all even number 1 to 55 is = 54


Q 59.Keep asking the user to enter numbers and add them to a total. Stop when the user enters 0. Then print the total sum.

In [85]:

total = 0
while n != 0:
    n = int(input("enter number ="))
    if n == 0:
        total += n
        print(total)


enter number = 12
enter number = 0


0


Q 60.Ask the user for a number. Print all its multiples from 1 to 100.

In [86]:
n = int(input("enter the number ="))

for i in range(1,101):
    if i % n == 0:
        print(i)

enter the number = 20


20
40
60
80
100


Q 61.Ask the user to enter a number. Find the sum of all even digits in that number.
Example: 2468 → 2 + 4 + 6 + 8 = 20

In [89]:
a = input("enter number")

sum =0
for i in a:
    if int(i) % 2 == 0:
        sum += int(i)
print(sum)

enter number 256


8


Q 63.Ask the user to enter a number n. Calculate and print the sum of squares of numbers from 1 to n.

In [90]:
n = int(input("enter the number ="))

sum = 0
for i in range(1,n+1):
    sum += i ** 2

print("sum of square numbers =",sum)

enter the number = 12


sum of square numbers = 650


Q 64.Ask the user to enter a number and print how many digits it has.

In [92]:
num = int(input("Enter a number"))
a = num 
count = 0

while a > 0:
    count += 1
    a //= 10 

print(count)    

Enter a number 123


3


Q 65.Ask the user how many numbers they want to enter (n). Accept n numbers, then print their total sum and average.

In [94]:
n = int(input("how many numbers they want to enter ="))
total = 0
for i in range(n):
    j = int(input("enter the number ="))
    total += j
    avg = total / n
print("sun of numbers =",total)
print("average of numbers =",avg)

how many numbers they want to enter = 3
enter the number = 1
enter the number = 5
enter the number = 7


sun of numbers = 13
average of numbers = 4.333333333333333


Q 66.Ask the user to input a total number of seconds. Convert and print it as minutes and seconds. Example: 130 seconds → 2 minutes, 10 seconds

In [96]:
n = int(input("enter second ="))
min = n //60
sec = n % 60
print(min,"minutes",sec,"seconds")

enter second = 222


3 minutes 42 seconds


Q 67.Ask the user to input time in hours. Convert and print the equivalent in seconds.

In [97]:
t = int(input("enter time in hours ="))
min = t * 3600
print(min,"second")

enter time in hours = 5


18000 second


Q 68.Ask the user for two numbers: a and b. Print all numbers from a to b. If a > b, print in reverse.

In [99]:
a = int(input("enter 1 number ="))
b = int(input("enter 2 number ="))
if a > b:
    for i in range(a,b-1,-1):
        print(i)
else:
    for i in range(a,b+1):
        print(i)

enter 1 number = 10
enter 2 number = 2


10
9
8
7
6
5
4
3
2


Q 69.Ask the user for a number n. Use a loop to calculate the product of all numbers from 1 to n.

In [100]:
n = int(input("enter a number ="))
count = 1
for i in range(1,n + 1):
    count *= i
print(count)

enter a number = 10


3628800


## Type Conversion: 
## 1.Implicit Type conversion
## 2.Explicit type conversion

Q 70.Ask the user to input two integers. Add them and print the result as a float using type conversion.

In [101]:
a = int(input("enter 1 number ="))
b = int(input("enter 2 number ="))
add = a + b
print(float(add))

enter 1 number = 12
enter 2 number = 14


26.0


Q 71.Ask the user to input a number n. Use a loop to print "Hello" exactly n times.

In [102]:
n = int(input("enter number to print hello ="))

for i in range(1,n+1):
    print("hello")
    

enter number to print hello = 2


hello
hello


Q 72.Ask the user to enter a number n. Use a loop to print numbers from 1 to n, but skip all numbers that are divisible by 4.

In [104]:
n = int(input("enter the number ="))

for i in range(1,n):
    if i % 4 == 0:
        print("")
    else:
        print(i)

enter the number = 10


1
2
3

5
6
7

9


Q 73.Ask the user to input a number. Keep dividing it by 2 using a loop until it becomes less than 1. Print how many divisions were performed.

In [110]:
a = int(input("enter number ="))
count = 0

for i in range(a):
    print(i % 2)
    count += 1
print(count)


enter number = 10


0
1
0
1
0
1
0
1
0
1
10


Q 74.Ask the user to input two numbers, a and b. Use a loop to find the sum of all numbers between a and b (inclusive). Handle if a > b by swapping or using a conditional structure.

In [111]:
a = int(input("enter 1 number ="))
b = int(input("enter 2 number ="))
sum = 0

if a > b:
    a,b = b,a
    
for i in range(a,b+1):
    sum += i
print("sum of all number's =",sum)

enter 1 number = 12
enter 2 number = 14


sum of all number's = 39


Q 75.Ask the user to enter two numbers, a and b. Calculate and print the average of all numbers between them (inclusive).

In [112]:
a = int(input("enter 1 number ="))
b = int(input("enter 2 number ="))
count = 0
sum = 0
if a > b:
    a,b = b,a
print(a)
print(b)
    
for i in range(a,b+1):
    sum += i
    count += 1
    avg = sum / count
print(avg)

enter 1 number = 123
enter 2 number = 147


123
147
135.0


Q 76.Ask the user for a number. Keep multiplying it by 10 using a loop until it becomes greater than 1000. Print how many steps it took.

In [3]:
a = float(input("Enter number = "))

count = 0
while a <= 1000:
    a = a * 10  
    count += 1
print(count)


Enter number =  22


2


Q 77.Ask the user to enter a number n. Print all numbers from n to 1 that are not divisible by 3.

In [5]:
n = int(input("enter number ="))

for i in range(n,0,-1):
    if i % 3 != 0:
        print(i)

enter number = 10


10
8
7
5
4
2
1


Q 78.Write a program that:
Takes marks (0–100) for 5 subjects from the user.
Calculates the average.
Assigns a grade based on the average:
A (90–100)
B (80–89)
C (70–79)
D (60–69)
F (below 60)
Prints "Passed" if the grade is not F, otherwise “Failed”.

In [6]:
eng = int(input("enter marks of english ="))
math = int(input("enter marks of maths ="))
sci = int(input("enter marks of science ="))
geo = int(input("enter marks of geography ="))
mar = int(input("enter marks of marathi ="))
total = eng + math + sci + geo + mar
avg = (total / 500 )*100
if 90 <= avg < 100:
    print("you get A grade")
elif 80 <= avg < 89:
    print("you get B grade")
elif 70 <= avg < 79:
    print("you get C grade")
elif 60 <= avg < 69:
    print("you get D grade")
else:
    print("f")

enter marks of english = 56
enter marks of maths = 58
enter marks of science = 77
enter marks of geography = 85
enter marks of marathi = 99


you get C grade


Q 79.Write a program that:
Accepts a number n.
Finds and prints the sum of all prime numbers up to n.

In [8]:
n = int(input("enter number"))

total = 0

for i in range(2,n + 1):
    for j in range(2,i):
        if i % j == 0:
            break
print(i)
            

enter number 55


55


Q 80.Write a program that:
Takes a number as input.
Replaces each digit with its square.
Joins and prints the result as a new number.
Input: 123 → Output: 149

In [10]:
a = input("enter n number =")
result = ""

for digit in a:
    square = int(digit) ** 2
    result += str(square)
print(result)

enter n number = 123


149


Q 81.Ask the user for:
A start number
An end number
A step
Then:
Calculate and print the sum of all numbers in that range.
Example: Start = 1, End = 10, Step = 2 → Sum = 1 + 3 + 5 + 7 + 9 = 25

In [12]:
a = int(input("enter start number ="))
b = int(input("enetr end number ="))
c = int(input("enter step ="))

count = 0
sum = 0
for i in range(a,b,c):
    count += 1
    sum += i
    
print("count =",count)
print("sum =",sum)

enter start number = 10
enetr end number = 15
enter step = 2


count = 3
sum = 36


Q 82.Ask for:
Principal amount
Annual interest rate
Number of years
Times interest is compounded per year
Use the formula:  A = P (1 + r/n)^(nt)
Print final amount A.

In [14]:
p = float(input("enter pricipal ammount ="))
r = float(input("enetr rate of intrest ="))
n = float(input("enter number if year ="))
t = float(input("enter Times interest is compounded per year ="))

A = p*r*n/100
C = p *((1 + r /100)**n)
print("simple rate of intrest =",A)
print("compound rate of intrest =",C)

enter pricipal ammount = 125478
enetr rate of intrest = 12
enter number if year = 9
enter Times interest is compounded per year = 12


simple rate of intrest = 135516.24
compound rate of intrest = 347960.37632733484


Q 83.Ask the user for a number.
If divisible by 2, print "Divisible by 2"
If divisible by 3, add " and 3" to output
If divisible by 5, add " and 5" to output
If none apply, print "Not divisible by 2, 3, or 5"

In [16]:
num = int(input("enter a nunber ="))

if num % 2 == 0:
    print("Divisible by 2",num)
elif num % 3 == 0:
    print("Divisible by 3, add ",3,"in",num,"=",num + 3)
elif num % 5 == 0:
    print("Divisible by 5, add ",5,"in",num,"=",num + 5)
else:
    print("not divisible by 2,3 or 5")

enter a nunber = 1234


Divisible by 2 1234


Q 84.Find all twin prime pairs between two numbers. Twin primes differ by 2 (e.g., 11 and 13).

In [17]:
s = int(input("enter a number 1 ="))
e = int(input("enter a number 2 ="))

for n in range(s,e-1):
    count = 0
    for i in range(1,n+1):
        if n % i == 0:
            count += 1 
    count2 = 0
    for j in range(1,n+3):
        if (n+2) % j == 0 :
            count2 += 1
    if count == 2 and count2 == 2:
        print(n,"and",n+2)

enter a number 1 = 10
enter a number 2 = 30


11 and 13
17 and 19


Q 85.Input a range and print all numbers that are palindromes.

In [25]:
s = int(input("Enter starting number = "))
e = int(input("Enter ending numbe = "))

for n in range(s, e + 1):
    if str(n) == str(n)[::-1]:
        print("Number is palindrome:", n)


Enter starting number =  10
Enter ending numbe =  30


Number is palindrome: 11
Number is palindrome: 22


Q 86.A number is Harshad if it is divisible by the sum of its digits.
Example: 18 → 1+8 = 9 → 18 % 9 == 0 → Harshad

In [26]:
num = int(input("enter number ="))
sum = 0

for digit in str(num):
    sum += int(digit)
    
if num % sum == 0:
    print("number is harshed")
else:
    print("number is not harshed")


enter number = 10


number is harshed


Q 87.A triangular number is of the form n(n+1)/2. Check if the given number fits that pattern.

In [27]:
n = float(input("enter number ="))

t = n*(n+1)/2
print(t)

enter number = 10


55.0


Q 88.A Disarium number is one where the sum of its digits raised to the power of their positions is equal to the number.
Example: 135 → 1¹ + 3² + 5³ = 135

In [29]:
num = input("Enter number =")
total = 0
count = 1

for digit in num:
    total += int(digit) ** count
    count += 1

if total == int(num):
    print("Disarium number =",num)
else:
    print("not Disarium number =",num)

Enter number = 135


Disarium number = 135


Q 89.Write a python program to find Sum of Non-Prime Numbers in a Range

In [30]:
start = int(input("enter starting number ="))
end = int(input("enter ending number ="))
total = 0
for num in range(start, end + 1):
    if num < 2:
        total += num
    else:
        for i in range(2, num):
            if num % i == 0:
                total += num
                
print(total)

enter starting number = 14
enter ending number = 55


3966


Q 90.Check for Magic Number
A number is a magic number if the repeated sum of its digits equals 1.
Example: 1729 → 1+7+2+9 = 19 → 1+9 = 10 → 1+0 = 1

In [31]:
num = int(input("Enter number = "))

while num > 9:
    total = 0
    for digit in str(num):
        total += int(digit)
    num = total

if num == 1:
    print(" magic number")
else:
    print("not magic number")

Enter number =  1729


 magic number


Q 91.Find the Digital Root of a Number
Repeatedly sum digits until a single-digit number is left.
Input: 9875 → 9+8+7+5 = 29 → 2+9 = 11 → 1+1 = 2

In [32]:
n = int(input("Enter number ="))

while n > 9:
    total = 0
    for digit in str(n):
        total += int(digit)
    n = total

print(n)

Enter number = 9875


2


Q 92.Count All Numbers in a Range That Have No Zero Digit
Example: 104 has a zero → Exclude | 123 → Include

In [33]:
s = int(input("Enter start number ="))
e = int(input("Enter end number ="))

count = 0
for i in range(s, e + 1):
    if '0' not in str(i):
        count += 1

print("numbers with no zero digit",count)

Enter start number = 123
Enter end number = 159


numbers with no zero digit 34


Q 93.Find All 2-Digit Numbers Where Sum of Digits Squared Equals the Number
Example: 81 → 8 + 1 = 9 → 9² = 81

In [34]:
n = int(input("Enter number ="))

while n > 100:
    total = 0
    for digit in str(n):
        total += int(digit)** 2
    n == total
print(n)

Enter number = 81


81


Q 94.Take a user input and find the difference between the product and sum of digits of a number.

In [35]:
n = int(input("Enter number ="))
sum = 0
product = 1
for digit in str(n):
    sum += int(digit)
    product *= int(digit)

    
print("product of number's =",product)
print("sum of number's =",sum)
d = product - sum
print("difference detween product and sum",product ,"-", sum,"=",d)

Enter number = 147


product of number's = 28
sum of number's = 12
difference detween product and sum 28 - 12 = 16


Q 95.Write a python program to check whether a number is a Duck number (contains zero but not as the first digit)

In [36]:
n = input("Enter number =")

for digit in str(n):
    
    if int(digit) == 0:
        print("nor duck number")
        break
    else:
        print("duck number")
        break

Enter number = 102


duck number


Q 96.Write a python program to check whether a number is an Automorphic number.

In [38]:
n = int(input("Enter number ="))
squre = n ** 2
num = n
count = 0
while num > 0:
    count += 1
    num //= 10

last_digit = squre % 10 ** count
print("squre = ",squre)
if last_digit == n:
    print("automorphic number ")     
else:
    print("not automorphic number ")     

        




Enter number = 76


squre =  5776
automorphic number 


Q 97.Write a python program to check if a number is a Trimorphic number

In [39]:
n = int(input("Enter number ="))
cube = n ** 3
num = n
count = 0
while num > 0:
    count += 1
    num //= 10
    

last_digit = cube % 10 ** count
print("cube = ",cube)

if last_digit == n:
    print("trimorphic number ")    
else:
    print("not trimorphic number ")     

Enter number = 76


cube =  438976
trimorphic number 


Q 98.Write a python program to find the first digit of a number without converting to string.

In [42]:
num = int(input("Enter a number: "))
while num >= 10:
    num = num // 10

print("he first digit is =", num)

Enter a number:  4587


he first digit is = 4


Q 99.Given a list of names: ["Alice", "Bob", "Charlie", "David"], write a program that iterates through the list and prints "Found Charlie!" when "Charlie" is encountered, then exits the loop

In [43]:
names = ["Alice", "Bob", "Charlie", "David"]

for c in names:
    if c == "Charlie":
        print("found Charlie!")
        break
    else:
        print("not charlie")
        
        

not charlie
not charlie
found Charlie!


Q 100.Given a list of numbers: [10, 20, 33, 46, 55], write a program that only prints numbers divisible by 5. If a number is not divisible by 5, skip it using continue. 

In [44]:
numbers = [10, 20, 33, 46, 55]

for i in numbers:
    if i % 5 == 0:
        print(i)
    else:
        continue

10
20
55


Q 101.given list of numbers, e.g., [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], write a program that:
Uses continue to skip even numbers.
Uses break to exit the loop if a number greater than 7 is encountered.
Otherwise, it prints the odd numbers. 

In [45]:
n = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for i in n:
    if i % 2 == 0:
        continue
    elif i > 7:
        break
    elif i % 2 != 0:
        print(i)

1
3
5
7


Q 102.You have a list of numbers: data = [10, -5, 20, 0, 30, -15, 40]. Write a program that iterates through this list:
If a number is negative, use continue to skip it.
If a number is 0, use break to exit the loop entirely.
Otherwise, print the square of the number. 

In [46]:
data = [10, -5, 20, 0, 30, -15, 40]

for i in data:
    if i <= 0:
        continue
    if i == 0:
        break
    else:
        c = i ** 2
        print(c)

100
400
900
1600


Q 103.Write a while loop that continues to prompt the user to enter a positive number. If the user enters a non-positive number or invalid input (like text), print an error message and use continue to ask again. Only accept positive numbers and use break once a valid positive number is received.

In [47]:
n = int(input("enter number ="))

while n % 2 != 0:
    print("error, enter valid numbeer")
    n = int(input("enter number ="))


print("your number is ",n)

enter number = 123


error, enter valid numbeer


enter number = 0


your number is  0


Q 104.You have a list of student scores: scores = [85, 92, 78, 65, 95, 70, -1, 88, 55, 100]. Iterate through the list:
If a score is negative, consider it an invalid entry, print a warning message, and use continue to skip it.
If a score is 100, print "Perfect Score!" and use break to stop further processing (assuming you only need to acknowledge the first perfect score).
Otherwise, print the score and indicate if it's a passing score (70 or above) or a failing score.

In [48]:
scores = [85, 92, 78, 65, 95, 70, -1, 88, 55, 100]
print("SCORES LIST")
print(scores)
print(".....................................")

for i in scores:
    if i <= 0:
        print("warning massage !, score is low =",i)
        print(".....................................")
        continue
    if i == 100:
        print("perfect score ! =",i)
        print(".....................................")

        break
    elif i >= 70:
        print("pass, your score is above 70 =",i)
        print(".....................................")

    elif i <= 70:
        print("fail becouse your scores is bellow 70 =",i)
        print(".....................................")

SCORES LIST
[85, 92, 78, 65, 95, 70, -1, 88, 55, 100]
.....................................
pass, your score is above 70 = 85
.....................................
pass, your score is above 70 = 92
.....................................
pass, your score is above 70 = 78
.....................................
fail becouse your scores is bellow 70 = 65
.....................................
pass, your score is above 70 = 95
.....................................
pass, your score is above 70 = 70
.....................................
warning massage !, score is low = -1
.....................................
pass, your score is above 70 = 88
.....................................
fail becouse your scores is bellow 70 = 55
.....................................
perfect score ! = 100
.....................................


## Inbuild Function :

Inbuild Function's : Inbuilt functions in Python are the ready made functions provided by Python that you can use directly to perform our tasks.

## User Define Function :

User Define Function's : This function's are written by the user from scratch there is a structure pre-defined in python which contains different component of a function and it has to be follow for each user define function.

Q 105.Write a python Function to Check if a Number is Prime.

In [56]:
## A prime number is a whole number greater than 1 that has only two divisors = 1 and the number itself. 
def prime_number():
    num = int(input("enter number ="))
    if num > 1:
        for i in range(2,num):
            if num % i == 0:
                print("this is not a prime number =",num)
                break
            
            else:
                print("this is a prime number =",num)
    else:
        print("this is not a prime numbe =",num)

prime_number()

enter number = 5


this is a prime number = 5
this is a prime number = 5
this is a prime number = 5


Q 106.Write a function to calculate sum of digits of a number.

In [57]:
def sum():
    num = int(input("enter number ="))
    total = 0
    for i in str(num):
        total += int(i)
    print(total)
sum()

enter number = 123


6


Q 107.Write a python function to Find the Sum of the First N Natural Numbers.

In [58]:
def natural_numbers():
    n = int(input("enter number ="))
    total = 0
    count = 0
    
    for i in range(1,n + 1):
        total += int(i)
        count += 1
        
    print(total)
    
natural_numbers()

enter number = 10


55


Q 108.Write a python function to find the total number of vowels in a string .

In [59]:
def vowels():
    name = input("enter your name =")
   
    
    total = 0

    for n in name:
        if n == "a" or n == "e" or n == "o" or n == "i" or n == "u" :
            
            total += 1
            
    print("total numbers of vowela",total)
            
vowels()

    

enter your name = abhi


total numbers of vowela 2


Q 109.Write a python function to calculate distance between two points.

In [61]:
def distance():
    d1 = int(input("Enter start number ="))
    d2 = int(input("Enter end number ="))

    dis = d1 - d2
    print("distance between two point's =",dis)
distance()

Enter start number = 20
Enter end number = 12


distance between two point's = 8


Q 110.Write a python function to calculate area of triangle .

In [62]:
def area_of_triangle():
    b = float(input("enter base of a triangle ="))
    h = float(input("enter height of a triangle ="))
    area = 0.5 * b * h
    print("area of triangle =",area)
area_of_triangle()

enter base of a triangle = 123
enter height of a triangle = 25


area of triangle = 1537.5


Q 111.Write a python function to convert celsius temperature to Fahrenheit and vice versa.

In [63]:
def convert_temp():
    c = float(input("enter temperature in celsius ="))
    fehrenhreit = (c * 9 / 5) + 32
    
    print("temperature converted celsius to fehrenheit =",fehrenhreit)
    
    f = float(input("enter temperature in fahrenheit ="))
    celsius = (f - 32) * 5 / 9
    
    print("temperature converted fehrenheit to celsius =",celsius)

convert_temp()

enter temperature in celsius = 41


temperature converted celsius to fehrenheit = 105.8


enter temperature in fahrenheit = 103


temperature converted fehrenheit to celsius = 39.44444444444444


Q 112.Write a python function to calculate compound interest and simple interest.

In [64]:
def interest():
    principal = float(input("enter principal ammount ="))
    rate = float(input("enter rate of interest ="))
    time = float(input("enter number of year's ="))
    compound = float(input("enter compound interest ="))
    
    ## compound interest
    compound_interest = principal * (1 + rate / compound) ** (compound * time)
    c_interest = principal - compound_interest
    print(" ammount with compound interest is =",compound_interest)
    print("compound interest on ammount =",c_interest)

    ## simple interest
    simple_interest = (principal * rate * time) / 100
    print("amoount with simple interest =",simple_interest)
    print("simple interest on your moount =",simple_interest - principal)

interest()

enter principal ammount = 125478
enter rate of interest = 23
enter number of year's = 8
enter compound interest = 12


 ammount with compound interest is = 5.341954995561028e+49
compound interest on ammount = -5.341954995561028e+49
amoount with simple interest = 230879.52
simple interest on your moount = 105401.51999999999


Q 113.Write a menu driven program using functions for all arithmetic operations.

In [66]:
def menu_driven():
    a = int(input("enter 1st number ="))
    b = int(input("enter 2nd number ="))

    add = a + b
    sub = a - b
    multi = a * b
    div = a / b
    print("addition of number's =",add)
    print("substraction of number's =",sub)
    print("multiplication of number's = ",multi)
    print("division of number's =",div)

menu_driven()

enter 1st number = 20
enter 2nd number = 12


addition of number's = 32
substraction of number's = 8
multiplication of number's =  240
division of number's = 1.6666666666666667


Q 114.Write a function to print numbers when starting number and ending number is specified by the user.

In [67]:
def numbers():
    s = int(input("enter starting number ="))
    e = int(input("enter ending number ="))

    for i in range(s,e + 1):
        print(i)
numbers()

enter starting number = 10
enter ending number = 15


10
11
12
13
14
15


Q 115.Write a function to print “Welcome to Python, username”. The username should be entered by the user. 

In [68]:
def welcome():
    username = input("enter your name =")
    print("Welcome to Python",username)
welcome()

enter your name = abhijeet


Welcome to Python abhijeet


Q 116.Write a python function to generate all divisors of a number.

In [69]:
def divisors():
    n = int(input("enter number ="))
    for i in range(1,n):
        digit = int(i)
        if n % digit == 0:
            print(digit)
divisors()

enter number = 123


1
3
41


Q 117.Write a Python function to find the maximum of three numbers.

In [70]:
def max_number():
    a = int(input("enter 1 number ="))
    b = int(input("enter 2nd number ="))
    c = int(input("enter 3rd number ="))

    if a > b and a > c :
        print("this number are greater than other number's",a)
    elif b > a and b > c :
        print("this number are greater than other number's",b)
    else:
        print("this number are greater than other number's",c)

max_number()

enter 1 number = 12
enter 2nd number = 14
enter 3rd number = 45


this number are greater than other number's 45


Q 118.Write a Python function to create and print a list where the values are the squares of numbers between 1 and 30 (both included).

In [71]:
def square():
    a = 1
    b = 30
    sq = 0 
    count = 0
    for i in range(a,b + 1):
        sq = int(i) ** 2
        count += 1
        print(sq)
square()

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900


## Default Parameter :

Default Parameter : The Default Parameter refer's to the default value's specified during function decleration.

Q 119.Write a Python function to check whether a number falls within a given range.

In [79]:
def in_range(num, start, end):
    print(start <= num <= end)

in_range(1,2,3)


False


Q 120.Create a Python program with user-defined functions to calculate the area of a triangle. 

In [72]:
def area_of_rectangle():
    l = int(input("enter the lenght of rectangle ="))
    w = int(input("enter the width of rectangle ="))
    a = l * w
    print("area of rectangle is = ",a)
area_of_rectangle()

enter the lenght of rectangle = 125
enter the width of rectangle = 26


area of rectangle is =  3250


Q 121.Write a Python program that defines user-defined functions to calculate the volume of a cube and a sphere .

In [73]:
def cube():
    l = int(input("enter the side length of cube ="))
    valume = l ** 3
    print("valume of the cube =",valume)
    
    r = int(input("enter the redius of cube ="))
    sphere = 3/4 * 3.14 * (r ** 3)
    print("sphere of the cube =",sphere)


cube()

enter the side length of cube = 123


valume of the cube = 1860867


enter the redius of cube = 524


sphere of the cube = 338832275.52


Q 122.Write a Python program with a user-defined function is_right_triangle(side1, side2, side3) that takes the lengths of three sides of a triangle as input and returns True if it can form a right-angled triangle (using the Pythagorean theorem), and False otherwise. 

In [74]:
def is_right_triangle(side1, side2, side3):
    a = side1 + side2 + side3
    
    if a == 180:
        print("it's a traingle =",a)
    else:
        print("it's not a traingle =",a)
    
    

is_right_triangle(12,33,80)

it's not a traingle = 125


Q 123.Create a Python program with user-defined functions to calculate the volume and surface area of a cylinder. 

In [75]:
def cylinder():
    h = float(input("enter the height of cylinder ="))
    r = float(input("enter the redius of cylinder ="))
    
    valume = 3.14 * h * (r ** 2)
    
    print("valume of cylinder =",valume)
    
    surface =2 * 3.14 * r * h + 2 * 3.14 * r * 2
    
    print("surface area of cylinder =",surface)

cylinder()

enter the height of cylinder = 34
enter the redius of cylinder = 23


valume of cylinder = 56476.04
surface area of cylinder = 5199.84


Q 124.Write a Python program that defines a user-defined function calculate_square_area(side) which takes the side length of a square as input and returns its area. 

In [76]:
def calculate_square_area(side):
    area = side * side
    
    print("square area =",area)

calculate_square_area(22)
    

square area = 484


Q 125.Create a Python program with a user-defined function calculate_square_perimeter(side) that takes the side length of a square as input and returns its perimeter. 

In [80]:
def calculate_square_perimeter(side):
    perimeter = 4 * side
    print("perimeter of square =",perimeter)

calculate_square_perimeter(12)

perimeter of square = 48


Q 126.Write a Python program that defines a user-defined function calculate_hypotenuse(side1, side2) which takes the lengths of the two shorter sides (legs) of a right-angled triangle as input and returns the length of the hypotenuse

In [81]:
def calculate_hypotenuse(side1, side2):
    hypotenuse = (side1 ** 2 + side2 ** 2) ** 0.5
    print("hypotenuse of a traingle =",hypotenuse)

calculate_hypotenuse(10,20)

hypotenuse of a traingle = 22.360679774997898


Q 127.Write a Python function to evaluate a linear function:
f(x) = 3x + 7 for a given value of x.

In [82]:
def evaluate_a_linear_function():
    x = float(input("enter value of x ="))
    f = 3 * x + 7
    print("f(",x,") =",f)

evaluate_a_linear_function()    

enter value of x = 12


f( 12.0 ) = 43.0


Q 128.Write a function that takes coefficients a, b, and c of a quadratic equation
ax² + bx + c = 0   and returns the real roots.

In [83]:
def find_real_roots(a,b,c):
    d = b ** 2 - 4 * a * c
    if d < 0:
        print("no real roots")
    elif d == 0:
        root = (-b / (2 * a ))
        print("one real root =",root)
    else:
        root1 = (-b + d ** 0.5) / (2 * a )
        root2 = (-b - d ** 0.5) / (2 * a )
        print("two real roots =",root1,"and",root2)


find_real_roots(1,-3,2)

two real roots = 2.0 and 1.0


Q 129.Write a function that evaluates the expression:
f(x) = x² + 2x + 1 for any x.

In [84]:
def evaluates_the_expression(x):
    f = x ** 2 + 2 * x + 1
    print("f(",x,")",f)

evaluates_the_expression(20)
    

f( 20 ) 441


Q 130.Write a function that checks whether a given number x is a solution to the equation:
2x - 5 = 11

In [85]:
def solution_to_the_equation(x):
    solution = 2 * x - 5
    if solution == 11:
        print("condition true =",solution)
    else:
        print("condition false =",solution)
solution_to_the_equation(12)

condition false = 19


Q 131.Given an expression x² + 2ax + a², write a function that returns its factorized form as a string.

In [91]:
def factorized(a,x):
    f = x ** 2 + 2 * a * x + a ** 2
    print(x ** 2,"+",2+a)

factorized(10,12)

144 + 12


Q 132.Write a python program for a given a quadratic equation in standard form y = ax² + bx + c, find the vertex (h, k).

In [92]:
def find_vertex(a,b,c):
    h = -b / (2 * a)
    k = a * h ** 2 + b * h + c
    x = h
   
    y = a * x ** 2 + b * x + c
    print("vertex of equation =",y)
    print(h,k)

find_vertex(5,7,-1)

vertex of equation = -3.4499999999999997
-0.7 -3.4499999999999997


Q 133.Write a function that returns the sum of the first n natural numbers using the formula
S = n(n + 1)/2

In [93]:
def  natural_numbers(n):
    s = n * (n + 1) / 2
    print("sum of natural numbeer's =",s)

natural_numbers(25)

sum of natural numbeer's = 325.0


Q 134.Write a Python program that defines a user-defined function calculate_rhombus_area(diagonal1, diagonal2) which takes the lengths of the two diagonals of a rhombus as input and returns its area     

In [94]:
def calculate_rhombus_area(diagonal1, diagonal2):
    area = (diagonal1 * diagonal2) / 2
    print("calculate rhombus area =",area)

calculate_rhombus_area(45,66)

calculate rhombus area = 1485.0


Q 135.Create a Python program with a user-defined function calculate_rhombus_perimeter(side) that takes the side length of a rhombus as input and returns its perimeter.
Then, get user input for the side length and print the calculated perimeter. 

In [95]:
def calculate_rhombus_perimeter(side):
    perimeter = 4 * side
    print("rhombus perimeter =",perimeter)

calculate_rhombus_perimeter(99)

rhombus perimeter = 396


Q 136.Write a Python program that defines a user-defined function get_line_equation(x1, y1, x2, y2) which takes the coordinates of two points (x1, y1) and (x2, y2) and returns the slope and y-intercept of the line passing through them. The function should return a tuple (m, c) representing the slope (m) and y-intercept (c) in the slope-intercept form (y = mx + c). Handle the case of vertical lines (undefined slope) appropriately (e.g., return None for slope and the x-intercept). 

In [96]:
def get_line_equation(x1, y1, x2, y2):
    if x1 == x2:
        print("none intercept", x1)

    else:
        m = (y2 - y1) / (x2 - x1)
        c = m * x1 + y1
        print("slope m =",m ,"and y-intercepting line c",c)

get_line_equation(1,2,3,4)

slope m = 1.0 and y-intercepting line c 3.0


Q 137.Write a Python program that defines a user-defined function calculate_trapezium_area(base1, base2, height) which takes the lengths of the two parallel bases and the height of a trapezium (trapezoid) as input and returns its area.

In [97]:
def calculate_trapezium_area(base1, base2, height):
    area = 0.5 * ( base1 + base2 ) * height
    print("trapezium area =",area)

calculate_trapezium_area(10,20,40)

trapezium area = 600.0


Q 138.Write a Python program that defines a user-defined function calculate_dot_product(vec1_x, vec1_y, vec2_x, vec2_y) which takes the x and y components of two 2D vectors as input and returns their dot product.
Then, get user input for the components of two vectors and print their dot product.

In [98]:
def calculate_dot_product(vec1_x, vec1_y, vec2_x, vec2_y):
   ### vector1 = vec1_x * vec1_y
   ### vector2 = vec2_x * vec2_y
    vector1_vector2 = (vec1_x * vec1_y) + (vec2_x * vec2_y) 
    print(vector1_vector2)


calculate_dot_product(2,3,4,1)    
    

10


Q 139.Create a Python program with a user-defined function calculate_factorial(n) that takes a non-negative integer n as input and returns its factorial. The factorial of a number n is the product of all positive integers less than or equal to n. For example, 5 factorial (5!) is 5 * 4 * 3 * 2 * 1 = 120

In [99]:
def calculate_factorial(n):
    count = 0
    sum = 1
   
    
    for i in range(n , 1,-1):
        sum *= i
        count += 1
    print(sum)

calculate_factorial(5)

120


Q 140.Write a Python program that defines a user-defined function calculate_mean(numbers_list) which takes a list of numbers as input and returns their arithmetic mean (average). The mean is the sum of all numbers divided by the count of numbers.

In [100]:
def calculate_mean(numbers_list):
    count = 0
    sum = 0
    
    for i in numbers_list:
        
        sum += i
        
        count += 1
        
        mean = (sum / count )
        
    print(mean)

calculate_mean([1,2,3,4,5])        

3.0


Q 141.Write a Python program that defines a user-defined function sum_list_elements(numbers_list) which takes a list of numbers as input and returns the sum of all elements in the list. You should not use the built-in sum() function. Use a loop instead.

In [101]:
def sum_list_elements(numbers_list):
    sum = 0
    
    for i in numbers_list:
        sum += i
        
    print("sum of all element =",sum)

sum_list_elements([2,4,6,8])

sum of all element = 20


Q 142.Create a Python program with a user-defined function find_largest_element(numbers_list) that takes a list of numbers as input and returns the largest element in that list. You should not use the built-in max() function. Use a loop and a variable to keep track of the largest number found so far.

In [102]:
def find_largest_element(numbers_list):
    large = numbers_list[0]
    
    for i in numbers_list:
        
        if i > large:
            
            large = i
    print(large)
find_largest_element([1,2,3])

3


Q 143.Write a python Function to Check for Twin Primes
Two numbers are twin primes if they are both prime and differ by 2.

In [104]:
def twin_prime():
    start = int(input("enter 1st number ="))
    end = int(input("enter 2nd number ="))

    for n in range(start,end - 1):
        count = 0
        for i in range(1,n+1):
            if n % i == 0:
                count += 1
            count2 = 0
        for j in range(1,n+3):
            if (n + 2) % j == 0:
                count2 += 1
        if count == 2 and count2 == 2:
            print(n,"and",n+2)
twin_prime()

enter 1st number = 100
enter 2nd number = 200


101 and 103
107 and 109
137 and 139
149 and 151
179 and 181
191 and 193
197 and 199


Q 144.Write a python function to find  Greatest Common Divisor (GCD) using Euclid’s algorithm

In [105]:
def gcd_algo():
    a = int(input("enter 1st number ="))
    b = int(input("enter 2nd number ="))
    

    while b != 0:
        a,b = b, a % b
        print(a)

gcd_algo()

enter 1st number = 123
enter 2nd number = 154


154
123
31
30
1


Q 145.Write a python function to find Midpoint of a line segment

In [106]:
def Midpoint_of_line_segment(x1,y1,x2,y2):
    midpoint = (x, y) = ((x1 + x2)/2, (y1 + y2)/2)
    print(midpoint)
Midpoint_of_line_segment(1,2,3,4)

(2.0, 3.0)


Q 146.Write a python function to find Equation of the perpendicular bisector of segment (x1, y1)-(x2, y2)

In [2]:
def perpendicular_bisector_of_segment(x1,x2,y1,y2):
    mid_x = (x1 + x2) / 2
    mid_y = (y1 + y2) / 2 
    perp_slope = 1
    if x2 - x1 == 0:
    
        print("original line is vertical")
        return
    slope = (y2 - y1 ) / (x2 - x1)

    if slope == 0:
        print("original line is horizontal")
        return
    prep_slope = -1 / slope

    c = mid_y - prep_slope * mid_x
    print("The perpendicular bisector is y =", perp_slope + c)
    
        
    

perpendicular_bisector_of_segment(1,2,3,4)

The perpendicular bisector is y = 6.0


Q 147.Write roman_to_int(roman_str) that converts Roman numerals to integers without using dictionaries.

In [108]:
def roman_to_int(ro):
    
    if ro == "I" :
        print("1")
    elif ro == "V" :
        print("10")
    elif ro == "X" :
        print("100")
    elif ro == "D" :
        print("500")
    elif ro == "M" :
        print("1000")
    else :
        print(0)

roman_to_int("D")
    
    

500


Q 148.Write a python program to Calculate HCF Using Subtraction Method

In [113]:
def Calculate_HCF_Using_Subtraction_Method():
    a = int(input("enter 1st value ="))
    b = int(input("enter 2nd value ="))
    while a != b:
        if a > b:
            a =(a - b)
            
        else:
            b = (b - a)
        print("HFC is =",a)

Calculate_HCF_Using_Subtraction_Method()            
        

enter 1st value = 10
enter 2nd value = 50


HFC is = 10
HFC is = 10
HFC is = 10
HFC is = 10


Q 149.Write a python program Check for Buzz Number

A number is a Buzz Number if it ends with 7 or is divisible by 7.
Write is_buzz(n).

In [117]:
def is_buzz():
    num = int(input("enter number ="))
    if num % 10 == 7 or num % 7 == 0:
        print("it's buzz number =",num)

    else:
        print("is not buzz number =",num)

        
is_buzz()        

enter number = 7


it's buzz number = 7


Q 150.Write a python program to check Magic Number 

A number is a Magic Number if the sum of its digits is repeated until a single digit is obtained and that is 1.
Example: 199 → 1+9+9=19 → 1+9=10 → 1+0 = 1 → Magic

In [119]:
def magic_number():
    num = int(input("Enter number = "))
    while num > 9:
        total = 0
        for digit in str(num):
            total += int(digit)
            num = total
    if num == 1:
        print(" magic number")
    else:
        print("not magic number")

magic_number()

Enter number =  199


 magic number


Q 151.Write a python program to find Sum of First N Even Numbers

Write sum_of_evens(n) to return sum of first n even numbers manually.

In [120]:
def sum_of_evens():
    num = int(input("enter number ="))
    sum = 0
    for i in range(num):
        if i % 2 == 0:
            sum += i
    print(sum)

sum_of_evens()



enter number = 100


2450


Q 152.Write a python program to Check for Abundant Number

If the sum of the proper divisors of a number is greater than the number itself, it's abundant.
Example: 12 → 1+2+3+4+6 = 16 > 12 → Abundant

In [121]:
def abundant():
    num = int(input("enter number ="))
    sum = 0
    
    
    for i in range(1,num ):
        if num % i == 0:
            sum += i
    if sum > num:
        print("Abundant number = ",sum,">",num)
    else:
        print("not abundant ")
            
    
abundant()

enter number = 12


Abundant number =  16 > 12


Q 153. Write a python program to Check if Number is Composite 

A composite number has more than 2 factors.
Write is_composite(n).

In [124]:
def is_composite():
    num = int(input("enter number ="))

    if num < 4:
        print("is not composite number =",num)
    for i in range(2,num):
        if num % i == 0:
            print("composite number =",num)
        

            
 
is_composite()

enter number = 15


composite number = 15
composite number = 15


Q 154.Write a python program to Generate N Perfect Squares

Write generate_squares(n) to return the first n perfect squares using loops.

In [126]:
def generate_squares(num):

    if num < 0:
        print("invalid input")

    sqroot = int(num ** 0.5)
    if sqroot * sqroot == num :
        print("perfect square")
    else:
        print("not perfect square")
        
generate_squares(25)

perfect square


Q 155.Write a python program to Find Difference Between Sum of Squares and Square of Sum
For first n natural numbers, write difference(n) where:
sum1 = 1² + 2² + ... + n²
sum2 = (1 + 2 + ... + n)²
return sum2 - sum1

In [127]:
def difference(n):
    sum = 0
    count = 0
    for i in range(1,n+1):
        square = i ** 2
        square += i
        count += 1
        sum = count ** 2
    print("square of sum =",sum)
    print("sum of square =",square)
    difference = square - sum
    print("difference between sum of square and square of sum =",difference)

difference(20)

square of sum = 400
sum of square = 420
difference between sum of square and square of sum = 20


Q 156.Write a python program to Find the Nth Ugly Number
Ugly numbers have only 2, 3, or 5 as their prime factors. Write nth_ugly(n).

In [128]:
def nth_ugly(n):
    if n > 0:
        f = [2,3,5]
    for i in f:
        while n % i == 0:
            n = n // i
            if n == 1:
                print("ugly number =",n)
            else:
                print("not ugly number")
nth_ugly(8)

not ugly number
not ugly number
ugly number = 1


Q 157.Write a python program to Generate First N Prime Numbers Ending with 3
Write prime_ending_with_3(n) to generate such primes.

In [131]:
def prime_ending_with_3():
    for num in range(2, n+1):
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            if num % 10 == 3:
                print(num)
n = int(input("Enter number ="))
prime_ending_with_3()

Enter number = 50


3
13
23
43


Q 158.Write a python program to Check for Palprime Number
A Palprime is a number that is both a palindrome and a prime.
Write is_palprime(n).

In [132]:
def is_palprime(n):
    num = n
    reverce = 0
    while num > 0:
        reverce = reverce * 10 + num % 10
        num = num // 10

    
    if reverce != n:
        print("Not Palprime")
        return

    
    if n < 2:
        print("Not Palprime")
        return

    i = 2
    while i < n:  
        if n % i == 0:
            print("Not Palprime")
            return
        i += 1

    print("Palprime")


is_palprime(131)  

Palprime


Q 159.Write a python program to Check for Happy Prime

A Happy Prime is a number that is both prime and happy (sum of squares of digits eventually becomes 1).
Write is_happy_prime(n).

In [133]:
def is_prime(n):
    if n < 2:
        return False
    i = 2
    while i <= n // 2:
        if n % i == 0:
            return False
        i += 1
    return True

def is_happy(n):
    s = []
    while n != 1:
        if n in s:
            return False
        s = s + [n]  

        total = 0
        num = n
        while num > 0:
            digit = num % 10
            total += digit * digit
            num = num // 10
        n = total
    return True

def is_happy_prime(n):
    if is_prime(n) and is_happy(n):
        print(n, "is a Happy Prime")
    else:
        print(n, "is NOT a Happy Prime")


is_happy_prime(7)    

7 is a Happy Prime


Q 160. Write a python program to Check for Bouncy Number

A number is bouncy if its digits are neither in increasing nor decreasing order.
Write is_bouncy(n).
Example: 1234 → Not bouncy, 321 → Not bouncy, 132 → Bouncy.

In [134]:
def is_bouncy(n):
    increasing = False
    decreasing = False
    num = n
    last_digit = num % 10
    num = num // 10

    while num > 0:
        current_digit = num % 10
        if current_digit < last_digit:
            increasing = True
        elif current_digit > last_digit:
            decreasing = True
        last_digit = current_digit
        num = num // 10

        if increasing and decreasing:
            print("is bouncy",n)
            return

    print("it's not bouncy",n)


is_bouncy(1234)  



it's not bouncy 1234


Q 161.Write a python program to Check if Number Is Centered Hexagonal Number

A centered hexagonal number is in the form .
Write is_centered_hexagonal(n).

In [135]:
def is_centered_hexagonal(n):
    if n == 1:
        print("true")  
        return
    k = 1
    while True:
        value = 3 * k * (k - 1) + 1
        if value == n:
            print("true")
            return
        elif value > n:
            print("false")
            return
        k += 1


is_centered_hexagonal(1)   

true


Q 162.Write a python program to Check if Number Has Equal Even and Odd Digits

Write has_equal_even_odd(n) that returns True if the number has the same count of even and odd digits. 

In [136]:
def has_equal_even_odd(n):
    even = 0
    odd = 0
    num = n
    
    while num > 0:
        digit = num % 10
        if digit % 2 == 0:
            even += 1
        else:
            odd += 1
        num = num // 10
    c = even == odd
    print(c)


has_equal_even_odd(1234)  

True


Q 163.Write a python program to Check for Emirp Number

An emirp is a number that is prime and whose reverse is also prime (but not palindromic).
Example: 13 → 31, both prime → Emirp
Write is_emirp(n).

In [137]:
def is_prime(n):
    if n < 2:
        return False
    i = 2
    while i <= n // 2:
        if n % i == 0:
            return False
        i += 1
    return True

def reverse_num(n):
    reverce = 0
    num = n
    while num > 0:
        reverce = reverce * 10 + num % 10
        num = num // 10
    return reverce

def is_emirp(n):
    reverce = reverse_num(n)
    if n != reverce and is_prime(n) and is_prime(reverce):
        print("this is emiper",n)
    else:
        print("is not empire",n)


is_emirp(13) 

this is emiper 13


Q 164. Write a python program to Check if Product of Digits Equals the Number

Write is_product_equal(n) — return True if the product of digits equals the number.

In [138]:
def is_product_equal(n):
    product = 1
    num = n

    while num > 0:
        digit = num % 10
        product *= digit
        num = num // 10

    true = product == n
    print(true)



is_product_equal(5)


True


Q 165. Write a python program to Check if Digits Are All the Same

Write all_same_digits(n) to check whether all digits of the number are identical.
Example: 777 → True, 171 → False

In [139]:
def all_same_digits(n):
    for i in str(n):
        if str(i) == str(n):
            print("true")
        else:
            print("false")

all_same_digits(11)
    

false
false


Q 166.Write a python program to Find the Nth Centered Square Number

Centered square numbers follow the pattern: 1, 5, 13, 25...

Write centered_square(n) using the formula  or via loop logic.


In [140]:
def centered_square_numbers(n):
    for i in range(1, n + 1):
        c = i**2 + (i - 1)**2
        print("Term " , str(i) , "=" , str(c))


centered_square_numbers(10)

Term  1 = 1
Term  2 = 5
Term  3 = 13
Term  4 = 25
Term  5 = 41
Term  6 = 61
Term  7 = 85
Term  8 = 113
Term  9 = 145
Term  10 = 181


Q 167.Write a python program to Count Digits in Ascending Order
Write count_ascending_digits(n) that counts how many digits are greater than the digit before them.

In [141]:
def count_ascending_digits(n):


    prev = -1 
    count = 0
    digits = 0

   
    temp = n
    place = 1
    while temp >= 10:
        temp = temp // 10
        place *= 10

    while place > 0:
        digit = n // place 
        n = n % place       
        place = place // 10

        if prev != -1 and digit > prev:
            count += 1
        prev = digit

    print( count)


count_ascending_digits(12345)

4


Q 168.Write a python program to Check if All Digits Are Odd or Even
Write is_uniform_even_odd(n) — return True if all digits are even or all odd.

In [142]:
def is_uniform_even_odd(n):
  

    even_count = 0
    odd_count = 0
    length = 0

    if n == 0:
        print("all even true")
       

    temp = n
    while temp > 0:
        digit = temp % 10
        if digit % 2 == 0:
            even_count += 1
        else:
            odd_count += 1
        temp = temp // 10
        length += 1

    if even_count == length:
        print("all even true")
    elif odd_count == length:
        print("all odd true")
    else:
        print("mixed")


is_uniform_even_odd(1234)

mixed


Q 169.Write a python program to Find Maximum Product of Two Digits
Write max_digit_product(n) — returns the max product of any 2 digits of the number. 

In [1]:
def max_digit_product(n):


    max_product = 0
    digits = []

   
    temp = n
    digit_count = 0
    while temp > 0:
        digit_count += 1
        temp = temp // 10

    if digit_count < 2:
        return 0  


    digits = [0]*digit_count

    temp = n
    i = digit_count - 1
    while temp > 0:
        digits[i] = temp % 10
        temp = temp // 10
        i -= 1

 
    max_product = 0
    i = 0
    while i < digit_count:
        j = i + 1
        while j < digit_count:
            product = digits[i] * digits[j]
            if product > max_product:
                max_product = product
            j += 1
        i += 1

    print(max_product)


max_digit_product(1234)

12


Q 170.Write a python program to Check for Bi-Prime Number

A number is bi-prime if it is the product of 2 (not necessarily distinct) prime numbers.
Example: 6 → 2×3 → Bi-prime
Write is_biprime(n).

In [2]:
def is_prime(n):
    if n < 2:
        return False
    i = 2
    while i < n:
        if n % i == 0:
            return False
        i += 1
    return True

def is_biprime(n):
    i = 2
    while i <= n:
        if n % i == 0:
            j = n // i
            if is_prime(i) and is_prime(j):
                print("Bi-prime")
                
        i += 1
    print("Not Bi-prime")


is_biprime(17) 

Not Bi-prime


Q 171.Write a python program to Check for Descending Order of All Digits

Write is_digits_descending(n) — return True if each digit is smaller than or equal to the previous digit.


In [3]:
def is_digits_descending(n):
    
    prev_digit = 10  

    while n > 0:
        digit = n % 10  
        if digit > prev_digit:
            return False
        prev_digit = digit
        n = n // 10 

    return True

is_digits_descending(1234)

True

Q 173. Write a python program to Generate Numbers with All Unique Digits in Given Range
Write unique_digit_numbers(start, end) — only return numbers with no repeated digits.

In [1]:
def unique_digit_numbers(start, end):
    result = []

    for num in range(start, end + 1):
        n = num
        digits = [0] * 10
        unique = 1 

        while n > 0:
            d = n % 10
            if digits[d] == 1:
                unique = 0
                break
                
            digits[d] = 1
            n = n // 10

        if unique == 1:
            result = result + [num]  

    print(result)


unique_digit_numbers(10, 30)

[10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30]


Q 174. Write a python program to Check if Product of All Digits is Even

Write is_product_even(n) — return True if the product of all digits is an even number.

In [ ]:
def is_product_even(n):
    if n == 0:
        print("all even true")
        return

    num = n
    even = 1  

    while num > 0:
        digit = num % 10
        if digit % 2 != 0:
            even = 0
            break
        num = num // 10

    if even == 1:
        print("all even true")
    else:
        print("not all even")


is_product_even(1254)

Q 175.Write a python program to calculate determinant of 2x2 Matrix

In [3]:
def determinant_of_2x2_matrix(a, b, c, d):
    deter = (a * d) - (b * c)
    print("Determinant =", deter)


determinant_of_2x2_matrix(6,4,8,2)


Determinant = -20


Q 176.Write a python program to calculate Derivative of a Function (using finite difference)

In [4]:
def f(x):
    return x * x  

def calculate_derivative(x):
    h = 0.0001
    return (f(x + h) - f(x)) / h


calculate_derivative(3)

6.000100000012054

Q 178.Write a python function for calculating Partial Derivative (Numerical)

In [5]:
def f(x, y):
    return x * x + y * y

def Partial_Derivative_x(x, y):
    h = 0.0001
    return (f(x + h, y) - f(x, y)) / h

def Partial_Derivative_y(x, y):
    h = 0.0001
    return (f(x, y + h) - f(x, y)) / h


Partial_Derivative_x(2, 3)
Partial_Derivative_y(2, 3)

6.000100000012054

Q 181.Write a python function for Calculating Modular Exponentiation (a^b mod n)

In [6]:
def Calculating_Modular_Exponentiation(a, b, n):
    result = 1
    base = a % n
    exponent = b

    while exponent > 0:
        if exponent % 2 == 1:  
            result = (result * base) % n
        base = (base * base) % n
        exponent = exponent // 2
    return result

Calculating_Modular_Exponentiation(3, 200, 13)

9

Q 183.Write a python function to Check if a Point Lies Inside a Triangle (2D)

In [7]:
def area(x1, y1, x2, y2, x3, y3):
    return (x1*(y2 - y3) + x2*(y3 - y1) + x3*(y1 - y2))

def point_line_triangle(px, py, x1, y1, x2, y2, x3, y3):
    a1 = area(x1, y1, x2, y2, x3, y3)
    a2 = area(px, py, x2, y2, x3, y3)
    a3 = area(x1, y1, px, py, x3, y3)
    a4 = area(x1, y1, x2, y2, px, py)

   
    negative = (a2 < 0) or (a3 < 0) or (a4 < 0)
    positive = (a2 > 0) or (a3 > 0) or (a4 > 0)

    return not(negative and positive)

point_line_triangle(1, 1, 0, 0, 5, 0, 0, 5)  

True

Q 185.Write a python function to Find Nth Digit in a Concatenated Number Series

Given a number N, find the Nth digit in the series: 12345678910111213…

In [8]:
def find_digit_in_number(n):
    digit_length = 1
    count = 9
    start_num = 1

    while n > digit_length * count:
        n -= digit_length * count
        digit_length += 1
        count *= 10
        start_num *= 10

    target_num = start_num + (n - 1) // digit_length

    digit_index_in_num = (n - 1) % digit_length

    return int(str(target_num)[digit_index_in_num])

find_digit_in_number(8)

8

Q 187.Write a python function to Count Numbers That are Powers of 2 in a Range

Write a function to count numbers between L and R which are exact powers of 2.

In [10]:
def count_number_power():
    l = int(input("enter 1st number ="))
    r = int(input("enter 2nd number ="))
    count = 0
    for i in range(l,r+1):
        square = i * i
        if square > r:
            break
        if square >= l:
            count += 1
        print(count,square)
   
count_number_power()

enter 1st number = 1
enter 2nd number = 50


1 1
2 4
3 9
4 16
5 25
6 36
7 49


Q 188.Write a python function to find Largest Prime Factor

Given a number, return its largest prime factor without libraries.

In [11]:
def find_largest_prime_factor(n):
    max = 1
    for fac in range(1,n):
        if n % fac == 0:
            

            max = fac
    print("largest factor =",max)

    if max <= 1:
        print("not a prime factor =",max)
        return

    for i in range(2, max):
        if max % i == 0:
            print("not a prime factor =",max)
            return

    print("is prime factor =",max)

    
find_largest_prime_factor(10)      

largest factor = 5
is prime factor = 5


Q 189.Write a python program to Generate N Digit Numbers with Alternating Even and Odd Digits

Generate numbers with patterns like: 2, 3, 2, 3... or 1, 4, 1... where even and odd digits alternate.

In [12]:
def even_odd_digits(n):
    even_digit = 2
    odd_digit = 1
    
    for even_digit in str(n):
        if int(even_digit) % 2 == 0:
            print("even digits = ",even_digit)
            
    for odd_digit in str(n):
        if int(odd_digit) % 2 != 0:
            print("odd digits",odd_digit)
          

even_odd_digits(123456789)

even digits =  2
even digits =  4
even digits =  6
even digits =  8
odd digits 1
odd digits 3
odd digits 5
odd digits 7
odd digits 9


Q 190.Write a python function to Find Difference Between Largest and Smallest Digit

Given a number, find the difference between largest and smallest digit.

In [13]:
def difference_large_small():
    n = int(input("enter number ="))
    large = 0
    small = 9
    for digit in str(n):
        d = int(digit)
        if d > large:
            large = d
        if d < small:
            small = d

    print("large digit =",large)
    print("small digit =",small)

    difference = large - small
    print("Difference Between Largest and Smallest Digit",difference)
        
        
    
difference_large_small()    

enter number = 123


large digit = 3
small digit = 1
Difference Between Largest and Smallest Digit 2


Q 191.Write a python function to Generate All Primes Whose Digits Are All Prime

Only include primes where each digit is also a prime (2, 3, 5, 7).

In [15]:
def all_digit_are_prime():
    n = int(input("enter number ="))

    for digit in str(n):
        d = int(digit)
    if d <= 1:
        print("not a prime digit number =",n)
        return

    for i in range(2, d):
        if d % i == 0:
            print("not a prime digit number =",n)
            return

    print("prime digit number =",n)

        
all_digit_are_prime()        
        

enter number = 233


prime digit number = 233


Q 192.Write a python function to Find the Closest Number Greater Than N That Has All Even Digits

Start at N+1, keep checking until all digits are even.

In [16]:
def Closest_Number_Greater():
    n = int(input("Enter a number: "))

    for num in range(n + 1, 1000000): 
        for digit in str(num):
            if int(digit) % 2 != 0:
                break  
        else:
           
            print("closest even number greater than n =", num)
            break

Closest_Number_Greater()
    

Enter a number:  100


closest even number greater than n = 200


Q 193.Write a python function to Count All 3-Digit Numbers That Are Palindromes and Divisible by Sum of Digits
Example: 121, 131, 141, etc., and divisible by 1+2+1, 1+3+1 etc.

In [19]:
def find_palindrom_number():
    n = int(input("Enter a number: "))
    

    for i in range(10,n):
        num = i
        reversed_num = 0 

        while num > 0:
            digit = num % 10
            reversed_num = reversed_num * 10 + digit
            num = num // 10

        if i == reversed_num:
            print("Palindrome number =", i)
            sum = 0
            for digit in str(i):
                sum += int(digit)
        
        
            print("sum of digit =",digit," + ",digit ,"=",sum)

       
        

find_palindrom_number()


Enter a number:  121


Palindrome number = 11
sum of digit = 1  +  1 = 2
Palindrome number = 22
sum of digit = 2  +  2 = 4
Palindrome number = 33
sum of digit = 3  +  3 = 6
Palindrome number = 44
sum of digit = 4  +  4 = 8
Palindrome number = 55
sum of digit = 5  +  5 = 10
Palindrome number = 66
sum of digit = 6  +  6 = 12
Palindrome number = 77
sum of digit = 7  +  7 = 14
Palindrome number = 88
sum of digit = 8  +  8 = 16
Palindrome number = 99
sum of digit = 9  +  9 = 18
Palindrome number = 101
sum of digit = 1  +  1 = 2
Palindrome number = 111
sum of digit = 1  +  1 = 3


Q 194.Write a python function to Count All 2-digit Numbers with Digits in Geometric Progression

Example: 24 → 2, 4 → ratio = 2 → valid

In [20]:
def Geometric_Progression():
    n = int(input("enter number ="))
    count = 0

    for num in range(10,n+1):
        a = num // 10
        b = num % 10
        if a == 0 or b == 0:
            continue

        if a % b == 0 or b % a == 0:
            print(num)
            count += 1
    print("count =",count)


Geometric_Progression()
    

enter number = 24


11
12
13
14
15
16
17
18
19
21
22
24
count = 12


Q 195.Write a function called birthday that takes in three parameters (month, day, and year) and returns it in the format month/day/year. For example, birthday(11, 17, 1990) should return "11/17/1990" and birthday(7, 5, 2004) should return “7/5/2004".

In [21]:
def birthday(month,day,year):
    print(day,"/",month,"/",year)
birthday(11,25,2003)

25 / 11 / 2003


Q 196.Write a function called address that combines 3 different string address parameters (city, state, and zip) and returns a user’s address. After the city and state inputs, add a comma and a space. For example, address('Pune', 'MH', '411041') should return "Pune, MH, 411041”.

In [22]:
def address_parameters(city,state,zip):
    print(city,state,zip)
address_parameters("pune,","maharastra,",4111202)

pune, maharastra, 4111202


Q 197.Write a program to find out the prime factors of a number. Example: prime factors of 56 - 2, 2, 2, 7

In [24]:
def find_prime_factor(n):
    
    for fac in range(2,n):
        if n % fac == 0:
            print("factor =",fac)

    if fac <= 1:
        print("not a prime factor =",fac)
        return

    for i in range(2, fac):
        if fac % i == 0:
            print("not a prime factor =",fac)
            return

    print("is prime factor =",fac)

    
find_prime_factor(22)      
            

factor = 2
factor = 11
not a prime factor = 21


Q 198.Write a function sumPdivisors() that finds the sum of proper divisors of a number. Proper divisors of a number are those numbers by which the number is divisible, except the number itself. For example proper divisors of 36 are 1, 2, 3, 4, 6, 9, 18¶

In [25]:
def sumPdivisors(num):
    sum = 0
    for i in range(1,num+1):
        if num % i == 0:
            print("divisors =",i)
            sum += i
    print("sum of divisors =",sum)
sumPdivisors(36)

divisors = 1
divisors = 2
divisors = 3
divisors = 4
divisors = 6
divisors = 9
divisors = 12
divisors = 18
divisors = 36
sum of divisors = 91


Q 200.Write a python function to calculate simple interest and compound interest 

In [26]:
def si_compound():
    p = int(input("enter principal ammount ="))
    r = int(input("enter rate of intrest ="))
    t = int(input("enter number of years ="))
   
    si = (p * r * t) / 100
    print("compound intrest is =",si)
    compound_amount = p * (1 + (r / 100)) ** t
    compound_intrest = compound_amount - p
    print("compound intrest is =",compound_intrest)

si_compound()
    

enter principal ammount = 125478
enter rate of intrest = 23
enter number of years = 2


compound intrest is = 57719.88
compound intrest is = 64357.66619999998


Q 201.Write a python function to create a countdown timer, take the start and end number from the user

In [27]:
def start_end_number():
    s = int(input("enter starting number ="))
    e = int(input("entrt ending number ="))
    for i in range(s,e + 1):
        print(i)

start_end_number()


enter starting number = 10
entrt ending number = 20


10
11
12
13
14
15
16
17
18
19
20


Q 202.Write a python program to print multiplication of the digits in the number entered by the user, add 2 to each digit and then multiply

In [28]:
def digit_multiplication():
    num = int(input("enter number ="))
    multi = 0
    for digit in str(num):
        digit = int(digit)
        digit += 2
        multi = digit * num
        print(multi)
digit_multiplication()

enter number = 10


30
20


Q 203.Write a python function to take 5 numbers from the user, sort the numbers in ascending order.

In [30]:
def ascending_order_in_list(num):
    
    
    for digit in str(num):
        
        for digit2 in digit:
            
            if digit2 >= digit:
                print(digit)
data = [1,2,3,4,5]            
result = ascending_order_in_list(data)
print(result)

[
1
,
 
2
,
 
3
,
 
4
,
 
5
]
None


Q 205.Write a function that returns the alternating sum of digits.
For example: num = 1234 → 1 - 2 + 3 - 4 = -2

In [31]:
def alternating_sum_of_digits(num):
    sum = 0
    sign = 1

    for digit in str(num):
        sum += sign * int(digit)
        sign *= -1

    print(sum)

alternating_sum_of_digits(1234)

-2


Q 207.Write a python function to Check if a Number is Equal to Product of Its Digits Plus Sum of Its Digits

Example:
num = 123
Sum = 1+2+3 = 6, Product = 1×2×3 = 6
Check: 123 == 6 + 6 

In [32]:
def Equal_to_Product():
    num = int(input("enter number ="))
    sum = 0
    product = 1
    for digit in str(num):
        digit = int(digit)
        sum += digit
        product *= digit

    check = sum + product
    if check == num:
        print("both are equal =",check,num)

    else:
        print("both not equal=",check,num)


Equal_to_Product()    

enter number = 123


both not equal= 12 123


Q 208.Write a python function to Digit Reversal + Original = Palindrome

Check if reversing a number and adding to the original creates a palindrome.
E.g., num = 56 → 56 + 65 = 121 → palindrome

In [33]:
def reverce_original_palindrome():
    num = int(input("enter number ="))
    original = num
    reverse = 0

    
    while num > 0:
        
        
        digit = num % 10
        reverse = reverse * 10 + digit
        num = num // 10
    addition = original + reverse
    print("original ",original,"+","reverce",reverse,"=",addition)

    temp = addition
    reverce_addition = 0

    while temp > 0:

        digit = temp % 10
        reverce_addition = reverce_addition * 10 + digit
        temp = temp // 10

    if addition == reverce_addition:
        print("palimdrome")
    else:
        print("not palindrome =")
        

reverce_original_palindrome()
    

enter number = 56


original  56 + reverce 65 = 121
palimdrome


Q 209.Write a python function to Count All Digits Greater Than the Digit to Their Right

e.g., num = 954213 →
9 > 5 
5 > 4 
4 > 2 
2 > 1 
1 > 3 
→ Count = 4

Q 210.Write a python function to Create Number from Sum of Digits at Even and Odd Indexes

e.g. num = 123456 →
Even index digits (1-based): 2+4+6 = 12
Odd index digits: 1+3+5 = 9
New number = 912

In [34]:
def Even_and_Odd_Indexes():
    num = int(input("enter number ="))
    
    even = 0
    odd = 0

    for even_digit in str(num):
        
        even_digit = int(even_digit)
        
        if even_digit % 2 == 0:
            even += even_digit
            
    print("even digit =",even)
            
    for odd_digit in str(num):
        odd_digit = int(odd_digit)
        
        if odd_digit % 2 != 0:
            odd += odd_digit
    
    print("odd number =",odd)

    new_number = str(odd) + str(even)
    print("new number =",str(new_number))

Even_and_Odd_Indexes()
    
            

enter number = 123456


even digit = 12
odd number = 9
new number = 912


Q 211.Write a python function to Reverse Only Even Digits in a Number

e.g. num = 12345678 → Even digits: 2, 4, 6, 8 → Reverse → 8,6,4,2
Final output: 18345672

In [35]:
def Reverse_Only_Even_Digits():
    num = int(input("enter number = "))
    even = 0
    temp = 0  

    
    for digit in str(num):
        digit = int(digit)
        if digit % 2 == 0:
            print("even digit's =", digit)
            
            temp = temp * 10 + digit

    even_reverse = 0
    while temp > 0:
        digit_reverse = temp % 10
        even_reverse = even_reverse * 10 + digit_reverse
        temp = temp // 10

    print("reverse even digit's =", even_reverse)

Reverse_Only_Even_Digits()


enter number =  12345678


even digit's = 2
even digit's = 4
even digit's = 6
even digit's = 8
reverse even digit's = 8642


## Variable Length Arguement:

Variable Length Arguement: these arguement are used to pass multiple value as arguement during function call. 

## *args :

*args : These are used to pass multiple value during function call.

## **kwargs :

**kwargs : **kwargs are used to accept multiple value of keyword arguement the ** is used to specify kwargs,it then convert's the arguement into dictionary where every key is keyword and the value assciated with the keyword is the value for that respective key.

Q 212.Create a function custom_sum(*args, **kwargs) that calculates the sum of all numbers passed via *args, and then applies modifications from **kwargs. Modifiers can be:
"add": add this value to the sum
"subtract": subtract this value from the sum
"multiply": multiply the result by this value
"divide": divide the result by this value (integer division only)

In [36]:
def sum_s(*args,**kwargs):
    total = 0
    for i in args:
        total += i
    print(total)
    result = total

    for k,v in kwargs.items():
        if k == "add":
            result += v
            print("addition =",result)
        if k == "sub":
            result -= v
            print("substraction =",result)
        if k == "multi":
            result *= v
            print("multiplication =",result)
        if k == "divisor":
            result //= v
            print("division =",result)
            

        print(result)
    

sum_s(2,3,4,5,add = 5,sub = 5,multi = 5,divisor = 5)
        

14
addition = 19
19
substraction = 14
14
multiplication = 70
70
division = 14
14


Q 213.Write a function keyword_counter(*args, **kwargs) that counts how many times each keyword argument value appears in *args.

In [37]:
def keyword_counter(*args,**kwargs):
    for key,value in kwargs.items():
        count = 0
        for item in args:
            if item == value:
                count += 1
        print(key ,str(count))
keyword_counter(1,2,4,1,2,2,3,a = 1,b = 2, c= 3)
        
        

a 2
b 3
c 1


Q 214.Write a function print_args(*args) that prints each value from *args on a new line.

In [38]:
def print_args(*args):
    for i in args:
        print(i)
print_args(1,2,3,4,5)


1
2
3
4
5


Q 216.Write a function create_profile(**kwargs) that creates and returns a dictionary representing a user profile with the given keyword arguments

In [39]:
def create_profile(**profile):
    for k,v in profile.items():
        print(k,v)
create_profile(name ="abc",age =22,city ="pune",work = "data")

name abc
age 22
city pune
work data


Q 217.Write a function get_keys(**kwargs) that returns a list of all the keys passed as keyword arguments.


In [40]:
def get_keys(**kwarge):
    for k,v in kwarge.items():
        print(k)
get_keys(name ="abc",age =22,city ="pune",work = "data")

name
age
city
work


Q 218.Write a function multiply_args(*args) that multiplies all numeric positional arguments and returns the result. If none are numeric, return 1.

In [41]:
def multiply_args(*args):
    multi = 1
    for i in args:
        
        multi *= i
        if i == 0:
            print(1)
    print(multi)
    
multiply_args(2,0,4,5)
    

1
0


Q 219.Dynamic Email GeneratorRequirements:

Takes the recipient’s name (positional)

Accepts any number of lines in the body via *args

Accepts optional settings (**kwargs), like sender, subject, and signature

Prints the formatted email

In [42]:
def generate_email(recipient, *body, **options):
    print("To:", recipient)
    if 'subject' in options:
        print("Subject:", options['subject'])
   
    for line in body:
        print(line)
   
   

generate_email("abhi", "from : vikas",subject="job application")


To: abhi
Subject: job application
from : vikas


Q 220.Create Character Profile for a Game Requirements:

Accepts character class as first argument

Accepts any number of skills via *args

Accepts keyword attributes via **kwargs (like strength, agility, magic, etc.)

In [43]:
def Profile_for_Game_Requirements(clas , *args, **kwargs):
    print("class =",clas)
    for skill in args:
        print("skill =",skill)

    for k,v in kwargs.items():
        if 'strength' in k:
            print("strength =",v)
            
Profile_for_Game_Requirements("frist" , "runner", strength = "1000m")
            

class = frist
skill = runner
strength = 1000m


Q 221.Write a function object_builder(name, *args, **kwargs) that creates a dictionary representing an object.
name becomes the "name" field.
All values in *args become entries under "values" list.
All key-value pairs in **kwargs go under a "properties" sub-dictionary.

In [44]:
def object_builder(name, *args, **kwargs):
    print("name =",name)

    for value in args:
        print("values =",value)

    for k,v in kwargs.items():
        print("properties =",k,v)
object_builder("abhijeet", 123, running ="fast",drive ="currect" )


name = abhijeet
values = 123
properties = running fast
properties = drive currect


Q 222.Write a function create_student_profile(name, *scores, **weights) that:
Accepts name as the first argument.
Accepts any number of scores in *scores (assume test scores).
Accepts keyword arguments as subject weights (e.g., math=2, english=1).
Returns a dictionary

In [45]:
def create_student_profile(name, *scores, **weights):
    print("Student Name  =",name)

    for test_score in scores:
        print("Student Test Scores =",test_score)

    for k,v in weights.items():
        print("Student Subjects Scores =",k,v)

create_student_profile("vansh", 87, math =23,englist =34)

Student Name  = vansh
Student Test Scores = 87
Student Subjects Scores = math 23
Student Subjects Scores = englist 34


Q 223.Create a function sales_report(region, *sales, **bonuses) where:
region: region name (e.g., "East")
*sales: list of daily sales amounts
**bonuses: keyword bonuses by day (e.g., day1=100, day3=50)
Return a dictionary with:
region
sales list
total bonus
number of days

In [46]:
def sales_report(region, *sales, **bonuses):
    print("Region =",region)

    for amount in sales:
        print("Daily Sales amount =",amount)

        
    total_bonuses = 0
    for k,v in bonuses.items():
        
        print("Bonuses by day =",k,v)
        total_bonuses += v

        
    print("Total Bonuses =",total_bonuses)

sales_report("pune",1000,day1 =100,day2 = 40, day3 = 50)
        
        

Region = pune
Daily Sales amount = 1000
Bonuses by day = day1 100
Bonuses by day = day2 40
Bonuses by day = day3 50
Total Bonuses = 190


Q 224.Write a function account_summary(account_type, *transactions, **adjustments) that:
account_type: like "savings", "checking"
*transactions: deposit/withdrawal values (positive/negative)
**adjustments: like interest=50, fees=10

In [47]:
def account_summary(account_type, *transactions, **adjustments):
    print("Account Type :",account_type)

    total_transaction = 0
    for value in transactions:
        total_transaction += value
        print("Total Trasaction =",total_transaction)
    
    total_adjustment = 0
    for k,v in adjustments.items():
        print("Adjustments =",k,v)

        total_adjustment += v
    print("Total Adjustment =",total_adjustment)

    final_balance = total_transaction - total_adjustment
    print("Final Ammount =",final_balance)

account_summary("Saving",700,800,-500,200,intrest = 100,fees =50)

Account Type : Saving
Total Trasaction = 700
Total Trasaction = 1500
Total Trasaction = 1000
Total Trasaction = 1200
Adjustments = intrest 100
Adjustments = fees 50
Total Adjustment = 150
Final Ammount = 1050


Q 225.Write a function grade_exam(student, *marks, **penalties) that:
Accepts the student's name
Takes any number of marks (e.g., per section)
Accepts deductions via key words (e.g., late=5, cheating=10)
Return total score after all penalties.

In [48]:
def grade_exam(student, *marks, **penalties):
    print("Student Name =",student)

    total_marks = 0
    for mark in marks:
        print("Student marks in Exam =",mark)
        total_marks += mark
    print("Student total marks in Exam =",total_marks)

    deduction = 0
    for k,v in penalties.items():
        print("panelties on student marks =",k,v)

        deduction += v
    print("deduction of panelties in marks =",deduction)

    total_score = total_marks - deduction 

    print("total score after all penalties =",total_score)

grade_exam("Samarth",45,55,60,70,88,late = 5,cheating = 10)


        

Student Name = Samarth
Student marks in Exam = 45
Student marks in Exam = 55
Student marks in Exam = 60
Student marks in Exam = 70
Student marks in Exam = 88
Student total marks in Exam = 318
panelties on student marks = late 5
panelties on student marks = cheating 10
deduction of panelties in marks = 15
total score after all penalties = 303


Q 227.Write a function check_perfect_numbers(*args) that:
Accepts multiple integers via *args
Returns a list of only those numbers that are perfect numbers
A perfect number is a number that is equal to the sum of its proper divisors (excluding itself). Example: 6 → divisors: 1, 2, 3 → sum: 6

In [49]:
def check_perfect_numbers(*args):

    for num in args:

        divisor_sum = 0
        for i in range(1,num):
            if num % i == 0:
                divisor_sum += i
                

        if divisor_sum == num:
            print("perfect number =",num)

   


check_perfect_numbers(2,3,4,5,6,7,8)

perfect number = 6


Q 228.Write a function filter_divisible(divisor, *args) that returns a list of numbers from args divisible by divisor.


In [50]:
def filter_divisible(divisor, *args):
    print("divisor =",divisor)
    

    
    for num in args:
        if num % divisor == 0:
            print(divisor,"divisible by divisor =",num)

filter_divisible(8 ,10,20,37,65,78,56,65,96,88,300)

divisor = 8
8 divisible by divisor = 56
8 divisible by divisor = 96
8 divisible by divisor = 88


Q 229.Write a function is_prime(num) that returns True if num is prime, else False.


In [51]:
def is_prime(num):
    if num < 2:
        return False

    for i in range(2, num):
        if num % i == 0:
            return False

    return True
is_prime(5)

True

Q 230.Write a function count_divisors(*args) that returns a dictionary mapping each number to the count of its positive divisors.


In [53]:
def count_divisors(*args):
    
    for num in args:
        count = 0
        for d in range(1,num):
            if num % d == 0:
                count += 1
        print(count)
count_divisors(10)       

3


Q 231.Write a function sum_of_powers(power, *args) that computes the sum of each number raised to the given power (power is a positive integer).

In [54]:
def sum_of_powers(power, *args):
    print("Power of each number =", power)
    
    sum_power = 0
    
    for num in args:
        result = num ** power
        print("Power of", num, "=", result)
        sum_power += result

    print("Sum of powers =", sum_power)


sum_of_powers(2,5,4)


Power of each number = 2
Power of 5 = 25
Power of 4 = 16
Sum of powers = 41


Q 232.Write count_items(a) that returns how many elements are in list a without using len (iterate and count manually).

In [55]:
def count_items(a):
    
    count = 0
    for element in a:
        count += 1
    print("elements in list =",count)
    return count

list = [1,2,3,4,5]
result = count_items(list)
print(result)

elements in list = 5
5


Q 233.Write mean(a) that returns the arithmetic mean. You must compute both the total and the count via loops you write yourself.

In [56]:
def mean(a):
    count = 0
    total = 0
    for element in a:
        count += 1
        total += element

    mean_value = total / element
    print("mean value =",mean_value)
    return mean_value

data = [1,2,3,4,5]
result = mean(data)
print(result)

mean value = 3.0
3.0


Q 234.Write min_value(a) and max_value(a) that return the smallest and largest elements using only comparisons in a loop.

In [57]:
def min_value(a):
    min_value = a[0] 
    
    for element in a:
        if element < min_value:
            min_value = element
    print("min element in a =",min_value)
    return min_value

def max_value(a):
    max_value = a[0]

    for element in a:
        if element > max_value :
            max_value = element
    print("max element in a =",max_value)
    return max_value

data_min = min_value([12,54,87])
data_max = max_value([45,65,78])
print(data_min,data_max)
            

min element in a = 12
max element in a = 78
12 78


Q 235.Write data_range(a) that returns max_value(a) - min_value(a) using your own functions from (Q3).

In [58]:
def min_value(a):
    min_val = a[0]
    
    for element in a:
        if element < min_val:
            min_val = element
    print("min element in a =",min_val)
    return min_val

def max_value(a):
    max_val = a[0]

    for element in a:
        if element > max_val :
            max_val = element
    print("max element in a =",max_val)
    return max_val

def data_range(min_value,max_value):
    
    range_count = 0
    for data in range(min_value,max_value + 1):
        range_count += 1
        
        print("data range of min and max =",data)
    print("total range between min and max =",range_count)

min_result = min_value([12,54,87,56])
max_result = max_value([20,5,14,3])
result = data_range(min_result,max_result)
print(result)
        

min element in a = 12
max element in a = 20
data range of min and max = 12
data range of min and max = 13
data range of min and max = 14
data range of min and max = 15
data range of min and max = 16
data range of min and max = 17
data range of min and max = 18
data range of min and max = 19
data range of min and max = 20
total range between min and max = 9
None


Q 236.Write stddev_population(a) that returns population standard deviation using your own square root function sqrt_newton(x)

In [59]:
def standard_daviation(a):
    # total number of elements
    n = 0
    for _ in a:
        n += 1

    # sum of numbers
    total = 0
    for value in a:
        total += value

    # calculate mean of numbers
    average = total / n

    # each data point, subtract the mean and square the result
    square_diff_sum = 0
    for value in a: 
        result = value - average
        square = result * result
        square_diff_sum += square

    # calculate variance 
    variance = square_diff_sum / n

    # take the square root to get standard deviation
    root = variance ** 0.5

    return root


data = [8, 5, 7, 9, 6]
r = standard_daviation(data)
print(r)

1.4142135623730951


Q 237.Write z_score(a, value) that returns the z-score of value using your mean and stddev_population.

In [60]:
def mean_val(a):
    # number in a
    n = 0
    for _ in a:
        n += 1
    # total of number's
    total = 0
    for value in a:
        total += value

    # average of number's (mean)
    average = total / n
    return average

def stddev_population(a):
    # calculating sum of difference 
    n = 0
    sum_diff_square = 0
    for value in a:
        average = mean_val(a)
        difference = value - average
        square = difference * difference
        sum_diff_square += square
        n += 1

    # variance for square root
    variance = sum_diff_square / n
    # root 
    root = variance ** 0.5
    return root

def z_score(a, value):
    # compute mean(average)
    mean = mean_val(a)
    # compute standard daviation
    root = stddev_population(a)
    # handle if root of zero using loop
    if root == 0:
        return root
    z = (value - mean) / root
    return z
    




a = [1,2,3,4,5]
value = 4
result = z_score(a,value)
print(result)

0.7071067811865475


Q 238.Write covariance(x, y) (population) given two equal-length lists. Compute means and the sum of cross-deviations in one or two passes; verify lengths manually.

In [61]:
def variance(x,y):
    # count the length of both list x and y
    n_x = 0
    for _ in x:
        n_x += 1
    n_y = 0
    for _ in y:
        n_y += 1

    # check if both list are same
    if n_x != n_y:
        return "both list are same"

    # calculate sum of element
    total_x = 0
    for value in x:
        total_x += value

    total_y = 0
    for value in y:
        total_y += value

    # calculate mean of list's
    mean_x = total_x / n_x
    mean_y = total_y / n_y

    # calculate variance using stddev
    sum_diif_square = 0
    i = 0
    while i < n_x:
        diff_x = x[i] - mean_x
        diff_y = y[i] - mean_y
        sum_diif_square += diff_x * diff_y
        i += 1

    variance = sum_diif_square / n_x
    return variance

x = [1,2,3,4,5]
y = [6,7,8,9,8]
result = variance(x,y)
print(result)

1.2


Q 239.Write geometric_mean(a) using only loops and your nth_root_newton(value, n) (implement nth root via Newton’s method). Handle zeros/negatives per your chosen definition (e.g., return None if any value ≤ 0).

In [62]:
def nth_root_newton(value,n):
    x = value / n
    max_iteration = 1000
    tolerance =1e-10
    for _ in range(max_iteration):
        # applying newton formula
        next_x = (1 / n) * ((n - 1) * x + value / (x ** (n - 1)))
        # chech converagence (check difference)
        diff = next_x - x

        if diff < tolerance and -diff < tolerance:
            return next_x
            # converaged
        x = next_x

    return x
    

def geometric_mean(a):
    # multiply number together
     # count no.of values
    multi = 1
    count = 0
    for value in a:
        multi *= value
        count += 1
        

   


    
    return nth_root_newton(multi , count)
    
data = [1,2,3,4,5]
result = geometric_mean(data)
print(result)

2.605171084697352


Q 240.Write trimmed_mean(a, k) that removes the k smallest and k largest values (use your own sort and manual counting) and returns the mean of the remaining values; handle edge cases when 2k ≥ N

In [63]:
def large_small(a):
    k_small = a[0]
    k_large = a[0]

    for value in a:
        if value < k_small:
            k_small = value
            
        if value > k_large:
            k_large = value

    return k_small, k_large

data = [1,2,3,4,5]

result = large_small(data)
print("smallest =",result[0])
print("largest =",result[1])

smallest = 1
largest = 5


Q 241.Write cumulative_frequency(counts) that returns cumulative counts list using only loops and manual addition.

In [64]:
def cumulative_frequency():
    count = [1, 2, 3, 4, 5]
    total = 0
    result = []
    for i in count:
     total += int (i)   
     result += [total]
    print(result)
cumulative_frequency()    

[1, 3, 6, 10, 15]


Q 242.Write a python function to Generate All Numbers Whose Digits Sum to N

In [65]:
def generate_numbers(n):

    count = 0
    sum = 0
    for num in range(n):
        
        for num2 in range(num):
            sum = num + num2
            
            if sum == n:
                print("number",num,"and",num2,"sum equal to number =",num,"+",num2,"=",n)
generate_numbers(10)

number 6 and 4 sum equal to number = 6 + 4 = 10
number 7 and 3 sum equal to number = 7 + 3 = 10
number 8 and 2 sum equal to number = 8 + 2 = 10
number 9 and 1 sum equal to number = 9 + 1 = 10


Q 243.Write a function egyptian_fraction(p, q) that takes two integers p (numerator) and q (denominator) and returns a list of denominators representing the sum of distinct unit fractions (1/k) that add up to p/q.

In [66]:
def egyption_fraction(a,b):

    
    while a != 0:
        x = (b + a - 1) // a
        print("1/" +str(x) ,"=", a ,"/" , b," ",end=" ")
        
        
        a = a * x - b
        b = b * x


    print()

        
a = 5
b = 6
egyption_fraction(a,b)

1/2 = 5 / 6   1/3 = 4 / 12   


Q 245.Write a function is_carmichael(n) that checks if a positive integer n is a Carmichael number using Korselt’s Criterion:
Square-Free: n must not be divisible by any prime squared (i.e., no repeated prime factors).
Divisibility Condition: For every prime factor p of n, (p - 1) must divide (n - 1).

In [68]:
def is_prime(n):
    
    for num in range(1,n+1):
        if n % num == 0:
            
            print(num)
            
            if num <= 1:
                is_prime = True

                
                count = 0
                for prime in range(2,num+1):
                    if prime % num == 0:
                        print("not prime factor",num)
                        is_prime = False
                        break
            if is_prime:
                    count += 1
                    if num == 1:
                        continue
                    print("prime divisor =",num)
                    
       
            if count == 4:
                break


def is_carmichael(n):
    if is_prime(n):
        count = 0
        total = 0
        while count == 3:
            total = (num - 1 ) / (n - 1)
            count += 1

        
        print(total)
                                                                      
                        
is_carmichael(561)

1
3
prime divisor = 3
11
prime divisor = 11
17
prime divisor = 17


Q 246.Write a function legendre(a, p) that computes the Legendre symbol (a/p), which indicates whether an integer a is a quadratic residue modulo an odd prime p.

In [69]:
def function_legendre(a,p):
    a = a % p
    exponent = (p - 1) // 2
    result = 1
    for i in range(exponent):
        result = (result * a) % p
    if result == 1:
        print("number is legendre =",result)
    else:
        print("no match")

function_legendre(2,7)    

number is legendre = 1


Q 248.Write a program to find how many distinct pairs (a, b) of non-negative integers satisfy the equation a² + b² = n.

In [70]:
def distinct_pairs(n):

    count = 0
    square = 0
    for num in range(n):
        
        for num2 in range(num):
            square = (num ** 2) + (num2 ** 2)
            
            
            if square == n:
                print("number",num,"and",num2,"square equal to number =",num,"+",num2,"=",n)
distinct_pairs(1000)

number 26 and 18 square equal to number = 26 + 18 = 1000
number 30 and 10 square equal to number = 30 + 10 = 1000


Q 249.Write a program that reads an integer and returns the sum and the product of its first and last digits.

In [71]:
def small_large(a):
    small = a
    large = 1

    for digit in str(a):
        digit = int(digit)
        if digit < small:
            small = digit
            
        if digit > large:
            large = digit

    sum = small + large
    product = small * large

    print("small digit =",small)
    print("large digit =",large)
    print("sum of the small digit and large digit",small,"+",large,"=",sum)
    print("product of the small digit and large digit",small,"*",large,"=",product)
    
    

small_large(2345)

small digit = 2
large digit = 5
sum of the small digit and large digit 2 + 5 = 7
product of the small digit and large digit 2 * 5 = 10


Q 250.Write a program to calculate the Pearson correlation coefficient for two lists of equal length.

In [72]:
def Pearson_correlation_coefficient(*x,*y):
    # length of x
    n = 0
    for _ in x:
        n += 1

    # the sum of the products of corresponding x and y values
    # s = sum of the products
    # p = product
    # s_x = sum of all x value
    # s_y = sum of all y value
    # sq_x = sum of square of all x value
    # sq_y = sum of square of all y value
    for i in range(n):
        square = 0
        s_x = 0
        sq_x = 0
    for i in x:
        s_x += i
        square *= i
        sq_x += square

        s_y = 0
        s = 0
        square_y = 0
        sq_y = 0
        for j in y:
            s_y += j
            square_y *= j
            sq_y += square_y
            p = i * j
            s += p

    r = [n * s - s_x - s_y ] / [(n * sq_x - (s_x) ** 2 )] * [n * sq_y - (s_y) ** 2]
    return r

x = [1,2,3,4]
y = [5,6,7,8]
Pearson_correlation_coefficient(x,y)

            
            

SyntaxError: * argument may appear only once (1602912952.py, line 1)

Q 251.Write a program to calculate the mean absolute deviation of a list of numbers.

In [73]:
def mean_absolute_deviation(n):

    # no.of the list
    num = 0
    for _ in n:
        num += 1

    # sum no.of the value in list
    total = 0
    for value in n:
        total += value

    mean = total / num

    
    mad = 0
    for value in n:
        # absolute daviation
        abs_d = abs(value - mean) 
        # mean of the absolute daviation 
        mad += abs_d
     
    result = mad / num
    return result

data = [4,6,8,10]
result = mean_absolute_deviation(data)
print(result)

2.0


Q 252.Write a program that calculates the moving average of a list of numbers given a window size.

In [74]:
def calculates_moving_average():
    data = [20, 22, 24, 23, 25]
    window = 3
    mean1 = (20 + 22 + 24) / 3
    mean2 = (22 + 24 + 23) / 3
    mean3 = (24 + 23 + 25) / 3

    return mean1,mean2,mean3


calculates_moving_average()    

(22.0, 23.0, 24.0)

Q 253.1.Write a python function to Check Equality of Two Quadratic Roots Given coefficients a, b, c, print Equal Roots if b^2 − 4ac = 0, else Unequal Roots.

In [3]:
def Two_Quadratic_Roots(a,b,c):

    if b ** 2 - 4 *(a * c) == 0:
        return "equal roots"
    else:
        return "unequal roots"
Two_Quadratic_Roots(5,10,20)
        
    

'unequal roots'

Q 254. Write a python function to Compare Two Quadratics at x₀
Given x0 and two quadratics f(x)=a1x^2+b1x+c1, g(x)=a2x^2+b2x+c2, print which is larger at x0 or Equal.

In [4]:
def Compare_Two_Quadratics(a1,b1,c1,a2,b2,c2):
    x = int(input("enter x value ="))
    f_x = a1 * x ** 2 + b1 * x + c1
    g_x = a2 * x ** 2 + b2 * x + c2

    if f_x < g_x :
        return "g(x) is larger"
    if f_x > g_x :
        return "f(x) is larger"
    else :
        return "both are equal"
        
Compare_Two_Quadratics(5,6,4,7,8,9)    

enter x value = 12


'g(x) is larger'

Q 255.Write a python function to Compare Slopes of Perpendicular Lines Given slopes m1 and m2, print Perpendicular if m1*m2 = -1, else Not Perpendicular.

In [5]:
def Slopes_of_Perpendicular_Lines(m1,m2):

    if m1 * m2 == -1 :
        return "Perpendicular"
    else:
        return "Not Perpendicular"

Slopes_of_Perpendicular_Lines(0.5,-2)

'Perpendicular'

Q 256. Write a python function to  check Axis of Symmetry vs Given Point
For quadratic ax^2+bx+c, check if vertex x=−b/(2a) lies left of, on, or right of a given x0.

In [6]:
def check_Axis(a,b,c,x):
    
    vertex = -b / (2 * a)
    if vertex < x :
        return "vertex is left of the point"
    if vertex > x :
        return "vertex is right of the point"
    else:
        return "vertex is on the lies"

check_Axis(10,23,56,55)

'vertex is left of the point'

Q 257. Write a python function  for Equation of Circle Validity
Given equation coefficients x²+y²+Dx+Ey+F=0, print Valid Circle if (D²+E²−4F) > 0, else Invalid.

In [7]:
def Equation_of_Circle_Validity(x,y,D,E,F):
    coefficient = (x ** 2) + (y ** 2) + (D * x) + (E * y) + F
    circle = (D ** 2) + (E ** 2) - (4 * F)

    if circle > 0 :
        return "Valid Circle"
    else:
        return " Invalid Circle"
        
Equation_of_Circle_Validity(10,20,23,32,33)

'Valid Circle'

Q 258.Write a python function to calculate Distance Comparison Between Two Points Given (x1,y1), (x2,y2), (x3,y3), print whether P2 or P3 is closer to P1.

In [8]:
def Comparison_Between_Two_Points(x1,y1,x2,y2,x3,y3):
    p1 = x1 * y1
    p2 = x2 * y2
    p3 = x3 * y3

    p2 = p1 - p2
    p3 = p1 - p3
    if p2 < p3 :
        return "p2 closer to p1"
    if p2 > p3 :
        return "p3 closer to p1"
    else:
        return "not closer"

Comparison_Between_Two_Points(5,6,4,7,8,9)

'p3 closer to p1'

Q 259. Write a python function for checking Line Midpoint Condition
Given (x1,y1),(x2,y2) and a point (x,y), check if (x,y) is the midpoint.

In [9]:
def Line_Midpoint_Condition(x,y,x1,y1,x2,y2):
    midpoint_x = x1 + x2 / 2
    midpoint_y = y1 + y2 / 2

    if x == midpoint_x and y == midpoint_y :
        return "x,y is the midpoint"
    else:
        return "not midpoint"

Line_Midpoint_Condition(5,7,6,8,5,9)


'not midpoint'

Q 260.Write a python function to Compare Two Triangle Perimeters
Given two triangles (a,b,c) and (p,q,r), print which has Greater Perimeter or Equal.

In [10]:
def Two_Triangle_Perimeters(a,b,c,p,q,r):
    A = a + b + c
    B = p + q + r
    if A < B :
        return " B is greater than A"
    if A > B :
        return "A is greater than B"
    else:
        return "both trangle are equal "


Two_Triangle_Perimeters(12,32,45,87,89,12)    

' B is greater than A'

Q 261.Write a python function to Check if Diagonal Splits Rectangle Equally
Given rectangle sides l,b and diagonal length d, check Pythagoras: d² = l²+b². Print Yes or No.

In [11]:
def Pythagoras(l,b,d):
    D = d ** 2
    L = l ** 2
    B = b ** 2
    if D == L + B :
        return "Rectangle is Equal"
    else:
        return "Rectangle is not Equal"


Pythagoras(10,15,30)        

'Rectangle is not Equal'

Q 262. Write a python function to check Tangent Slope at Point on Circle
Given circle x²+y²=r² and point (x0,y0), print slope of tangent as −x0/y0 if valid (avoid division by zero).

In [12]:
def Tangent_Slope_of_circle(x,y):
    x_s = x ** 2
    y_s = y ** 2
    r2 = x_s + y_s
    x1 = 0
    y1 = 0
    tangent_point = (x_s - x1)/(y_s - y1)
    return tangent_point,r2

Tangent_Slope_of_circle(3,5)

(0.36, 34)

Q 263. Write a python function to check Similar Triangles Test (SSS ratio)
Given two triangles sides (a,b,c) and (p,q,r), check if ratios a/p = b/q = c/r. Print Similar or Not Similar.

In [13]:
def Similar_Triangles_Test_SSS_ratio(a,b,c,p,q,r):
    A = a / p
    B = b / q
    C = c / r
    if a == b and a == c :
        return "Similar"
    else:
        return "Not Similar"

Similar_Triangles_Test_SSS_ratio(5,6,4,7,2,9)

'Not Similar'

Q 264. Write a python function for Point Reflection Check
Given (x,y) and (x′,y′), check if second is reflection of first across x-axis, y-axis, or origin.

In [14]:
def Point_Reflection_Check(x,y,a,b):
    x_axis = (2 * a) - x
    y_axis = (2 * b) - y
    R = y_axis + x
    return x,R
Point_Reflection_Check(3,5,8,6)

(3, 10)

Q 265.Write a python function to check Midpoint Lying on Circle
Given circle (h,k,r) and line segment (x1,y1),(x2,y2), check if midpoint lies on circle.

In [15]:
def Midpoint_Lying_on_Circle(h,k,r,x1,y1,x2,y2):
    # midpoint
    midpoint_x = (x1 + x2) / 2
    midpoint_y = (y1 + y2) / 2

    # Check midpoint lies on the circle
    distance_squared = (midpoint_x - h) ** 2 + (midpoint_y - k) ** 2

    if distance_squared == r ** 2:
        return "midpoint lies on the circle"
    else:
        return "midpoint not lie on the circle"
mid_result = Midpoint_Lying_on_Circle(5,7,6,8,5,9,2)
print(mid_result)


midpoint not lie on the circle


Q 266.Write a python function to check Tangent vs Secant Line to Circle (Distance Method)
Given line ax+by+c=0 and circle (x−h)²+(y−k)²=r², print Tangent if distance from center = radius, Secant if less, else External.

In [16]:
def Tangent_vs_Secant(a,b,c,x,y,h,k):
    L_c = (a * x) + (b * y) + c
    C_r = (x - h) ** 2 + (y - k) ** 2
    D = L_c / C_r
    
    if D == C_r :
        return "less"
    else:
        return "External"

Tangent_vs_Secant(1,2,3,4,5,6,7)

'External'

Q 267. Write a python function to Compare Circumferences of Circle and Square
Given circle radius r and square side s, compare 2πr and 4s symbolically (just compare r vs 2s/π).

In [17]:
def Circumferences_of_Circle_and_Square(r,s):
    C = 2 * 3.14 * r
    S = s * 2
    
    if C < S :  
        return "Circumferences of Circle is less"
    if C > S :
        return "Circumferences of Circle is greater"
Circumferences_of_Circle_and_Square(25,34)

'Circumferences of Circle is greater'

Q 268. Write a python function to find the nth number in the Fibonacci series.

In [18]:
def fibo(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    else:
        return fibo(n - 1) + fibo(n - 2)
fibo(3)

2

Q 269. Write a recursive function to return the sum of first n natural numbers
ex: sum(5) = 5 + 4 + 3 + 2 + 1

In [19]:
def sum_n(n):
    if n == 0:
        return 0
    else:
        return n + sum_n(n - 1)
sum_n(5)

15

Q 270.Write a recursive function to calculate a ^ b without using exponent operator

In [20]:
def exponent(a,b):
    if b == 0:
        return 1
    else:
        return a * exponent(a,b-1)

exponent(2,3)

8

Q 271.Write a recursive function to count number of digits in the number entered by the user:

In [21]:
def count_d(n):
    if n == 0:
        return 0
    else:
        return 1 + count_d(n // 10)

count_d(123454)

6

Q 272.Write a function which takes user input and returns whether the number is prime or not.

In [22]:
def prime(n,i = 2):
    if n <= 1:
        return False
    if n == 2 or n == 3:
        return True
    if n % i == 0:
        return False
    if i * i > n:
        return True
    else:
        return prime(n,i + 1)
    


prime(117)
        

False

Q 273.Write a python function for  two spheres (x1,y1,z1,r1) and (x2,y2,z2,r2), check whether the smaller lies completely inside the larger.

In [23]:
def spheres(x1,y1,z1,r1,x2,y2,z2,r2):
    d = (x1 - x2) ** 2 + (y1 - y2) ** 2 + (z1 - z2) ** 2
    if d <= (r1 - r2) ** 2:
        return "A is completely inside the B"
    if d >= (r1 - r2) ** 2:
        return "B is completely inside the A"
    else:
        return "Both are equal"
spheres(2,3,4,5,6,7,8,9)

'B is completely inside the A'

Q 274. Write a python function for Perpendicular Vectors in 3D
Given vectors (a1,b1,c1) and (a2,b2,c2), check if Perpendicular (dot=0) or Not Perpendicular.                                                           

In [24]:
def vector_3d(a1,b1,c1,a2,b2,c2):
    Dot = (a1 * a2) + (b1 * b2) + (c1 * c2)
    if Dot == 0:
        return "Perpendicular Vector"
    else:
        return "Not Perpendicular Vector"
vector_3d(2,3,4,5,6,7)

'Not Perpendicular Vector'

Q 275. Write a python function to Find LCM using Recursion.

In [25]:
def GCD(a,b):
    if b == 0:
        return a
    else:
        return GCD(b , a % b)
def LCM(a,b):
    if a == 0 or b == 0:
        return 0
    else:
        return (a * b) // GCD(a, b)


GCD(12,22)


2

Q 276. Write a python function to Find GCD (Greatest Common Divisor) using recursion.

In [26]:
def GCD_n(a,b):
    if b == 0:
        return a
    else:
        return GCD_n(b , a % b)

GCD_n(30,60)

30

Q 277.Write a python function using recursion to find Sum of Alternate Digits (Odd Positions)

In [27]:
def sum_n(n):
    if n == 0:
        return 0
    if n % 2 != 0:
        return n + sum_n(n - 1)
    else:
        return sum_n(n - 1)
  

sum_n(30)

225

Q 278. Write a python function to find Product of Digits using recursion.

In [28]:
def product_of_digit(n):
    if n == 0:
        return 1
    else:
        return (n % 10) * product_of_digit(n // 10) 

product_of_digit(123)

6

Q 279. Write a python function to Print Number in Reverse using recursion.

In [29]:
def reverce(n,r_n = 0):
    if n == 0:
        return r_n


    last_digit = n % 10
    return reverce(n // 10, r_n * 10 + last_digit) 

reverce(123)

321

## Inbuild function

Q 280. Write a python program to Convert a list of floats to integers.

In [31]:
a = [12.02,52.25,12.55,1.0,22.36]
list = lambda x :[int(i) for i in x]

print("list in integer's type =")
print(list(a))


list in integer's type =
[12, 52, 12, 1, 22]


Q 281. Write a python program to Extract the unit digit of each number.

In [32]:
a = [12,58,69,45,78,36]
sub = list(map(lambda x : x % 10 ,a))
print("unit digit =",sub)

unit digit = [2, 8, 9, 5, 8, 6]


Q 282. Write a python program to Raise each number to the power of its index.

In [33]:
q = [5,6,7,8,9]

for index,p in enumerate (q,start = 1):
    n = p ** index

    print("number ",p,"**",index,"=",n)


number  5 ** 1 = 5
number  6 ** 2 = 36
number  7 ** 3 = 343
number  8 ** 4 = 4096
number  9 ** 5 = 59049


Q 283.Write a python program to Keep only numbers with exactly 3 digits.

In [34]:
d = [123,369,45,852,741,69,235,55,14,25,36]
num = list(filter(lambda x : x // 100 ,d))
print(num)

[123, 369, 852, 741, 235]


Q 284. Write a python program to Filter numbers which are not multiples of any number in [2, 3, 5].

In [35]:
f = [1,2,3,4,5,6,7,8,9,11,21,54,78,23,65,99]
z = list(filter(lambda x : x % 2 != 0 and x % 3 != 0 and x % 5 != 0,f))
print(z)

[1, 7, 11, 23]


Q 285.Write a python program to Find the number formed by multiplying digits of all numbers.

In [36]:
num = [12,32,65,89,78,45,12]
def mull(x):
    result = 1
    for digit in str(x):
        result *= int(digit)
    return result

map_result = map(mull,num)
print(list(map_result))
            

[2, 6, 30, 72, 56, 20, 2]


Q 286. Write a python program to Find the index of the number with the highest number of digits.

In [38]:
a = [5, 6, 7, 8, 9, 5, 8, 9, 7, 4, 1, 2, 5, 8, 6, 3]

max_digit = 0
max_index = 0

for index, num in enumerate(a, start=1):
    
    if num > max_digit:
        max_digit = num
        max_digit = index

print(max_digit)


8


Q 287. Write a python program to Sum all values whose index is a multiple of 3.

In [39]:
o = [5,6,7,8,9,5,8,9,7,4,1,2,5,8,6,3]
for index,p in enumerate (o,start = 1):
    if index % 3 == 0:
        print(index)



3
6
9
12
15


Q 288. Write a python program to Find the factorial of each number using map + lambda.

In [40]:
g = [2,3,4,5,6,7,8,9]
def fact(x):
    result = 1
    for i in range(1, x + 1):
        result *= i
    return result
map_result = map(fact, g)
print(list(map_result))

[2, 6, 24, 120, 720, 5040, 40320, 362880]


Q 289.Find the cube of the difference between each number and the maximum in the list.

In [41]:
j = [1,2,3,4,5,6]
def cube(x):
    
    cube = x ** 3
    diff = cube - x
    return diff


# difference between cube and each number
cube_result = map(cube,j)
print("difference between cube and each number")
print(list(cube_result))

def max_val(x):
    max_v = cube(x) - max(j)
    return max_v




# difference between max value and cube in list
max_result = map(max_val,j)
print("difference between max value and cube in list")
print(list(max_result))

difference between cube and each number
[0, 6, 24, 60, 120, 210]
difference between max value and cube in list
[-6, 0, 18, 54, 114, 204]


Q 290.Filter numbers that are divisible by the sum of their digits.

In [42]:
v = [52,45,65,32,89,14,99,4,123]

def sum_d(x):
    sum = 0
    for i in str(x):
        sum += int(i)
    return sum

f_result = list(filter(lambda z : sum_d(z) % z != 0 ,v))
print("numbers that are divisible by the sum of their digits =")
print(f_result)

numbers that are divisible by the sum of their digits =
[52, 45, 65, 32, 89, 14, 99, 123]


Q 291.Replace each number with the sum of its digits.

In [43]:
k = [52,45,65,32,89,14,99,4,123]

def sum_d(x):
    sum = 0
    for i in str(x):
        sum += int(i)
    return sum
        

# Replace each number with the sum of its digits.
k_result = map(sum_d,k)
print("Replace each number with the sum of its digits =")
print(list(k_result))



Replace each number with the sum of its digits =
[7, 9, 11, 5, 17, 5, 18, 4, 6]


Q 292. Using reduce(), concatenate a list of numbers into a single integer.

In [44]:
from functools import reduce
i = [1,2,3,4,5,6,7,8,9]


i_result = reduce(lambda x,y : str(x)+str(y),i)
print(i_result)

123456789


Q 293. Write a python program to Count Even Digits in a Number using recursion.

In [45]:
def sum_n(n):
    if n == 0:
        return 0
    if n % 2 != 0:
        return n + sum_n(n - 1)
    else:
        return sum_n(n - 1)
  

sum_n(30)

225

Q 294.count even digit in number

In [46]:
# 1.count even digit in number
def sum_n(n):
    if n == 0:
        return 0


    else:
        digit = n % 10
        return (1 if digit % 2 == 0 else 0) + sum_n(n // 10)



sum_n(1234)

2

 Q 295.Write a python program to Replace All Occurrences of 0 with 5 using recursion.

In [47]:
def Occrrences(n):
    if n == 0:
        return 0

    last_digit = n % 10
    if last_digit == 0:
        last_digit = 5


    return Occrrences(n // 10) * 10 + last_digit

Occrrences(12340)    



12345

Q 296.Write a python program to Find Number of Zeroes in a Number using recursion.

In [48]:
def Zeroes(n):
    if n == 0 :
        return 1

    if n < 10 or n == 0:
        return 0

    last_digit = n % 10
    remain_digit = n // 10
    
    if last_digit == 0:
        return 1 + Zeroes(remain_digit)
    else:
        return Zeroes(remain_digit)

Zeroes(1001)
    


2

Q 297. Write a python program to find Sum of Alternate Digits (Even Positions) using recursion.

In [49]:
def sum_n(n):
    if n == 0:
        return 0
    if n % 2 == 0:
        return n + sum_n(n - 1)
    else:
        return sum_n(n - 1)
  

sum_n(30)

240

 Q 298.Write a python program to find Sum of Square of Alternate Digits using recursion.

In [50]:
def square_digits(n,is_alternate = True):
    if n == 0:
        return 0
    last_digit = n % 10
    main_number = n // 10

    if is_alternate:
        return (last_digit ** 2) + square_digits(main_number ,False)
    else:
        return square_digits(last_digit,True)

square_digits(1234)
     

25

Q 299.Write a python program to find Count of Digits Greater than 5 using recursion.


In [51]:
def digits_5(n):
    if n == 0:
        return 0
    last_digit = n % 10

    count = 0
    if last_digit > 5:
        count = 1

    return count + digits_5(n // 10)

digits_5(123789)


3

Q 300.Write a python program to Convert each number into the reverse of its digits.

In [52]:
def reverce(n,reverce_n = 0):
    if n == 0:
        return reverce_n

    last_digit = n % 10

    return reverce(n // 10 ,reverce_n * 10 + last_digit)

reverce(1234)

4321

Q 301. Write a python program to Filter numbers where all digits are even.

In [54]:
v = [12,23,52,41,71,63,14,22]

def even_digit(x):
    for i in str(x):
        if int(i) % 2 != 0:
            return False
    return True

    
            

f_result = list(filter(even_digit, v))
print(f_result)


[22]


Q 302. Write a python program to Keep numbers where the product of digits is even.

In [57]:
a = [21, 55, 65, 89, 14, 75, 65, 22]

def product_digits(x):
    product = 1
    for i in str(x):
        product *= int(i)
    return product

a_result = list(map(product_digits, a))
print(a_result)


[2, 25, 30, 72, 4, 35, 30, 4]


Q 303. Write a python program to Find the sum of the minimum and maximum in a list using reduce.

In [58]:
from functools import reduce
a = [1,2,3,4,5,6,7,8,9]

def max(x,y):
    if x > y:
      return x
    else:
      return y

def min(x,y):
    if x < y:
      return x
    else:
      return y
        
maxn = reduce(max,a)
minn = reduce(min,a)

print(maxn)
print(minn)
print(maxn + minn)

9
1
10


Q 304.Write a python program to Count how many numbers in a list are greater than the average (use reduce to get average).

In [59]:
# many numbers in a list are greater than the average (use reduce to get average)
from functools import reduce
v = [1,2,3,4,5,6,58,65,78,41,55]
total = reduce(lambda x ,y : x + y,v)
numbers = 0
for _ in v:
    numbers += 1


avg = total / numbers
v_result = reduce(lambda a , s : a + 1 if s > avg else a,v,)
print(v_result)
    

        

6


Q 305. Write a python program to Use lambda in filter to keep numbers whose square ends in 1.

In [60]:
s = [2,3,4,5,6,7,8,9]
result = list(filter(lambda x: (x ** 2) % 10 == 1, s))

print(result)


[9]


Q 306.Write a python program to Filter numbers whose digit sum is even, then return their reversed forms.

In [61]:
# Filter numbers whose digit sum is even, then return their reversed forms.
w = [12,45,78,65,32,14,74,2,64,86,33]
def sum_even(x):
    total = 0
    for i in str(x):
        total += int(i)
    return total % 2 == 0

w_result = list(filter(sum_even,w))
print(w_result)

def reverce(x):
    reverce_num = 0
    
    while x > 0:
        last_digit = x % 10
        reverce_num = reverce_num * 10 + last_digit
        x = x // 10
    return reverce_num
r_result = list(map(reverce,w_result))
print(r_result)

    

[2, 64, 86, 33]
[2, 46, 68, 33]


Q 307. Write a python program to Map numbers to the difference between the number and its reverse.

In [62]:
# Map numbers to the difference between the number and its reverse.
f = [25,45,68,96,32,14,52]
def reverce_n(x):
    main_number = x
    reverce_num = 0
    while x > 0:
        last_digit = x % 10
        reverce_num = reverce_num * 10 + last_digit
        x = x // 10
    return reverce_num - main_number

f_result = list(map(reverce_n,f))
print(f_result)



    

[27, 9, 18, -27, -9, 27, -27]


Q 308. Write a python program to Filter numbers with even digit sums, map to their square, reduce to sum them.

In [63]:
e = [54,12,63,89,75,48,59]
# keep numbers whose digit sum is even
def sum_even(x): 
    sum = 0
    for i in str(x):
        sum += int(i)
        return sum % 2 == 0
even_sum = list(filter(sum_even,e))
print(even_sum)
# square those numbers
square_even = list(map(lambda x : x ** 2 ,even_sum))
print(square_even)

# add all the squared numbers together
add_even = reduce(lambda x ,y : x + y,square_even)
print(add_even)

[63, 89, 48]
[3969, 7921, 2304]
14194


Q 309.Write a python program to From a list of numbers, remove all that are prime, then return the product of remaining.

In [64]:
r = [2,3,4,5,6,7,8,9]
def prime(x):
    if x < 2:
        return False

    for i in range(2 ,x ):
        if x % i == 0:
            return False
    return True

def not_prime(x):
    if not prime(x):
        return x * x
    else:
        return False


non_prime = list(filter(lambda x : x is not False ,map(not_prime,r)))
print(non_prime)


[16, 36, 64, 81]


Q 310.Write a python program to Square numbers, keep only > 10, sum them.

In [65]:
from functools import reduce
t = [2,5,4,8,11,14,9]
def square(x):
    return x ** 2
square_num = list(map(square,t))
print("square of each number =")
print(square_num)
greater_10 = list(filter(lambda x : x > 10,square_num))
print("filter number those are greater than 10 =")
print(greater_10)
sum_num = reduce(lambda x,y : x + y,greater_10)
print("sum of those number this are greater than 10 =")
print(sum_num)


square of each number =
[4, 25, 16, 64, 121, 196, 81]
filter number those are greater than 10 =
[25, 16, 64, 121, 196, 81]
sum of those number this are greater than 10 =
503


Q 311.Write a python program to Convert a list of integers to their negatives.

In [66]:
z = [54,12,63,89,75,48,59]
def negative(x):
    if x > 0:
        return -x
    else:
        return x
num_negative = list(map(negative,z))
print(num_negative)

[-54, -12, -63, -89, -75, -48, -59]


Q 312.Write a python program to Keep only numbers where the sum of digits is odd.

In [67]:
k = [54,12,63,89,75,48,59]
def odd_sum(x):
    sum = 0
    for i in str(x):
        sum += int(i) 
    return sum % 2 != 0
sum_odd = list(filter(odd_sum,k))
print("numbers the sum of digits is odd =")
print(sum_odd)


numbers the sum of digits is odd =
[54, 12, 63, 89]


Q 313.Write a python program to Sort list by remainder when divided by 3.

In [68]:
a = [2,3,4,5,6,7,8,9]
def divide_by3(x):
    if x % 3 == 0:
        return x
a_result = list(filter(divide_by3,a))
print(a_result)
        
        

[3, 6, 9]


Q 314.Write a python program to Use enumerate() and map() to multiply value with its (1-based) position.

In [69]:
a = [2,9,3,4,5,6,7,8]

def multiply_index_value(index_value):
    i, v = index_value  # unpack tuple here, no indexing
    return i * v

result = list(map(multiply_index_value, enumerate(a, start=1)))
print(result)


[2, 18, 9, 16, 25, 36, 49, 64]


Q 315. Write a python program to Map each number to its absolute difference from 100

In [70]:
d = [258,741,963,456,789,123]
def abs_diff(x):
    diff = x - 100  # absolute difference means number1 - number2
    return diff

d_result = list(map(abs_diff,d))
print("number to its absolute difference from 100 =")
print(d_result)

number to its absolute difference from 100 =
[158, 641, 863, 356, 689, 23]


Q 316.Write a python program to Filter numbers with all non-zero digits.

In [71]:
a = [12,50,60,88,69,74,53,20,80,90]
def non_zero(x):
    if x % 10 == 0:
        return x
a_result = list(filter(non_zero,a))
print(a_result)

[50, 60, 20, 80, 90]


Q 317.Write a python program to Filter numbers that are square of any other number in the list.

In [72]:
w = [2,3,4,5,6,7,8,9,44,55,25,78,96,35,47,52,56,11,22,35,4,99]

def is_perfect_square(x):
    i = 1
    while i * i <= x:
        if i * i == x:
            return True
        i += 1
    return False

w_result = list(filter(is_perfect_square, w))
print(w_result)


[4, 9, 25, 4]


Q 318.Write a python program to Return True if a number is greater than 50, else False.

In [73]:
k = [2,3,4,5,6,7,8,9,44,55,25,78,96,35,47,52,56,11,22,35,4,99]
k_result = list(map(lambda x : x > 50 ,k))
print(k_result)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1]


Q 319.Write a python program to Subtract each number from the max value in the list.

In [74]:
from functools import reduce
a = [1,2,3,4,5,6,7,8,9]
# taking max value in list
def max(x,y):
    if x > y:
      return x
    else:
      return y
# taking min value in list
def min(x,y):
    if x < y:
      return x
    else:
      return y

        
maxn = reduce(max,a)
minn = reduce(min,a)

# after substract the each value from max 
def subs(x):
    return maxn - x


a_result = list(map(subs,a))
print(a_result)

print(maxn)
print(minn)


[8, 7, 6, 5, 4, 3, 2, 1, 0]
9
1


Q 320. Write a python program to Convert a list of 2-digit numbers into a list of digit sums.

In [75]:
a = [1,2,3,4,5,6,7,8,9]
sum = reduce(lambda x,y : x + y ,a)
print(sum)

45


Q 321. Write a python program to Filter numbers whose square ends with digit 6.

In [76]:
b = [1,2,3,4,5,6,7,8,9]
def square(x):
    return x ** 2

b_result = list(filter(lambda i : square(i) % 10 == 6,b))
print(b_result)


[4, 6]


Q 322. Write a python program to Count how many numbers are greater than 100.

In [77]:
f = [52,456,74,258,12,325,85,658]
def count_x(lst):    # when you need to do task with x value use lst aurgument in function
    count = 0
    for x in lst:
        if x > 100:
            count += 1
    return count
f_result = count_x(f)
print(f_result)

        
    

4


Q 323. Write a python program to Find the number with the minimum digit product.

In [78]:
b = [25,64,78,642,892,25,26]
def product(x):
    p = 1
    for digit in str(x):
        p *= int(digit)
    return p
p_result = list(map(product,b))
print(p_result)

def max(x,y):
    if x > y:
      return x
    else:
      return y
# taking min value in list
def min(x,y):
    if x < y:
      return x
    else:
      return y

        
maxm = reduce(max,p_result)
minm = reduce(min,p_result)
print(minm)
print(maxm)

[10, 24, 56, 48, 144, 10, 12]
10
144


Q 324. Write a python program to Use lambda + filter to return numbers with prime digit sum.

In [79]:
b = [25,64,78,642,892,25,26]
def summ(x):
    sum = 0
    for digit in str(x):
        sum += int(digit)
    return sum
sum_r = list(map(summ,b))
print(sum_r)



# Prime check function
def prime(n):
    if n < 2:
        return False
    i = 2
    while i * i <= n:
        if n % i == 0:
            return False
        i += 1
    return True

#  Filter prime digit sums
is_prime = list(filter(prime, sum_r))
print("Prime digit ", is_prime)



[7, 10, 15, 12, 19, 7, 8]
Prime digit  [7, 19, 7]


Q 325. Write a python program to Use lambda + map to return each number’s parity as string.

In [1]:
b = [25,64,78,67,892,25,26]

add = list(map(lambda x: "even" if x % 2 == 0 else "odd",b))
print(add)


['odd', 'even', 'even', 'odd', 'even', 'odd', 'even']


Q 326. Write a python program to Create a list of products of each number with its index.

In [2]:
c = [25,64,78,67,892,25,26]
def prod(x):
    product = 1
    for i in str(x):
        product *= int(i)
    return product
product_list = list(map(prod,c))

for index,value in enumerate(product_list,start = 1):
    print(index,value)

1 10
2 24
3 56
4 42
5 144
6 10
7 12


Q 327. Write a python program to Find the difference between sum of evens and odds.

In [3]:
from functools import reduce
h = [1,3,4,5,6,7,8,9]
# creating the list of even and odd numbers
def evenn(x):
    if x % 2 == 0:
        return x
       
def oddm(x):
  
    if x % 2 != 0:
        return x
even = list(filter(evenn,h))
odd = list(filter(oddm,h))
print(even)
print(odd)

# creating sum of even and odd numbers
def sum_even(even):
    sum_e = 0
    for value in even:
        sum_e += value
    return sum_e
def sum_odd(odd):
    sum_o = 0
    for value in odd:
        sum_o += value
    return sum_o
# substract even odd for gate defference   
e = sum_even(even)
o = sum_odd(odd)
print("difference between even and odd sum =")
print(o - e)
        

[4, 6, 8]
[1, 3, 5, 7, 9]
difference between even and odd sum =
7


Q 328. Given a list of integers and a divisor n, use filter and a lambda to return a list of all numbers divisible by n.

In [4]:
a = [25,12,45,887,69,325,45,74]
n = 5
list = list(filter(lambda x : x % n == 0,a))
print(list)



[25, 45, 325, 45]


Q 329. Given a list of integers and a single integer n, use filter to find all numbers that are co-prime with n. Then use map and reduce to find the sum of squares of these co-prime numbers.

In [1]:
from functools import reduce
s = [2,3,4,6,7,8,9,11,12,13,14,15,16,17,18,19,20]
n = 5


def gcd(x,y):
    while y:
        x, y = y, x % y
    return x

def are_coprime(x, n):
    return gcd(x, n) == 1

# check coprime
coprime = list(filter(lambda v : are_coprime(v, n),s))
# taking square of numbers
square = list(map(lambda a : a ** 2 , coprime))
# taking sum of squares
sum_square = reduce(lambda a , b: a + b ,square)

print("numbers that are co-prime with n =",coprime)
print("square of each number =",square)
print("sum of squares =",sum_square)




numbers that are co-prime with n = [2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 16, 17, 18, 19]
square of each number = [4, 9, 16, 36, 49, 64, 81, 121, 144, 169, 196, 256, 289, 324, 361]
sum of squares = 2119


Q 330. Given a list of numbers, use a combination of functions to find all amicable pairs within that list. Two numbers \(a\) and \(b\) are an amicable pair if the sum of the proper divisors of \(a\) is equal to \(b\), and the sum of the proper divisors of \(b\) is equal to \(a\) (\(a\ne b\)).

In [2]:
s = [2,3,4,6,7,8,9,11,12,13,14,15,16,17,18,19,20,220,284]

# Function to compute sum of proper divisors
def p_divisor(x):
    sum_d = 0
    for i in range(1, x):
        if x % i == 0:
            sum_d += i
    return sum_d

# Print sum of proper divisors
result = list(map(p_divisor, s))
print(result)

# Function to find and print amicable pairs
def amicable_pairs():
    i = 0
    while i < len(s):
        a = s[i]
        b = p_divisor(a)

        if b != a:
            j = 0
            while j < len(s):
                if s[j] == b:
                    if p_divisor(b) == a and a < b:
                        print(a, b)
                j += 1
        i += 1


amicable_pairs()


[1, 1, 3, 6, 1, 7, 4, 1, 16, 1, 10, 9, 15, 1, 21, 1, 22, 284, 220]
220 284


Q 331. Given a list of numbers, use map and a helper function to return a new list containing the sum of all divisors for each number. 

In [3]:
p = [2,3,4,6,7,8,9,11,12,13,14,15,16,17,18,19,20]

# helper fuction to divisible each number of list
def divisor(x):
    sum_divisor = 0
    for i in range(1,x):
        if x % i == 0:
            sum_divisor += i
    return sum_divisor

p_result = list(map(divisor,p))
print(p_result)
            

[1, 1, 3, 6, 1, 7, 4, 1, 16, 1, 10, 9, 15, 1, 21, 1, 22]


Q 332.Write a python function for Linear regression (OLS). To compute slope and intercept via formulas from sums; print fitted line and total absolute error (L1) and squared error (L2)

In [4]:
def linear_regretion(x,y):
    # sum_x = sum of all x values
    # sum-y = sum of all y values
    # sum_p_x = sum of product x values
    # sum_p_y = sum of product y value
    # sum_p_xy = sum of product of x and y values
    # sum_sq = sum of sqaured all x values
    # n_x = number of data point in x
    #
     # sum_x = sum of all x values
    sum_x = 0
    for i in x:
        sum_x += i
     # sum-y = sum of all y values
    sum_y = 0
    for j in y:
        sum_y += j

     # sum_p_x = sum of product x values
    sum_p_x = 0
    for i in x:
        sum_p_x = sum_p_x + i * i

    # sum_p_y = sum of product y value
    sum_p_y = 0
    for j in y:
        sum_p_y = sum_p_y + j * j

     # sum_p_xy = sum of product of x and y values
    sum_p_xy = sum_p_x + sum_p_y

    # sum_sq = sum of sqaured all x values
    sum_sq = 0
    for i in x:
        sum_sq = sum_sq + i ** 2

     # n_x = number of data point in x
    n_x = 0
    for _ in x:
        n_x += 1



    numerator = n_x * sum_p_xy - sum_x * sum_y
    denominator = n_x * sum_sq - sum_x * sum_x

    # calculating slope and intercept
    slope = numerator / denominator
    intercept = (sum_y - slope * sum_x) / n_x

    
    print("slope =",slope)
    print("intercept =",intercept)

x = [2,3,4,5,6]
y = [8,7,6,4,9]
result = linear_regretion(x,y)
print(result)
        

slope = 20.0
intercept = -73.2
None


Q 334.Write a python function for Linear Transformation of a List.Apply a linear transformation y = 2x + 3 to each number in a list.

In [5]:
a = [2,5,8,7,8]
def linear(x):
    y = 2 * x + 3
    return y
a_result = list(map(linear,a))
print(a_result)

[7, 13, 19, 17, 19]


Q 335.Write a python function for a list of radius of different circles, calculate the area of circle for each radius.

In [6]:
s = [5,69,47,85,54]
def radius(x):
    A = 3.14 * (x ** 2)
    return A
s_result = list(map(radius,s))
print(s_result)

[78.5, 14949.54, 6936.26, 22686.5, 9156.24]


Q 336.Write a python function to Evaluate a Polynomial at Given x Values, Evaluate f(x) = 3x² - 2x + 5 for each x in the list.

In [7]:
e = [65,89,14,75,32]
def polynominal(x):
    f_x = 3 * (x ** 2) - (2 * x) + 5
    return f_x
e_result = list(map(polynominal,e))
print(e_result)

[12550, 23590, 565, 16730, 3013]


Q 337. Write a python function to Filter Integer Solutions to Linear Equation, Find values of x where 2x + 3 = 11 (i.e., x = 4).

In [8]:
n = [2,3,4,5,6,7,8,9]
def integer(x):
    A = 2 * x + 3
    if A == 11:
        return x
n_result = list(filter(integer,n))
print(n_result)

[4]


Q 338. Write a python function to Calculate Weighted Average, Weighted average = Σ(value × weight) / Σ(weights).

In [9]:
from functools import reduce
weight = [56,89,75,20,60]
value = [2,5,8,6,3]
sum_value = reduce(lambda x , y: x + y , value)
sum_weight = reduce(lambda i , j : i + j , weight)
sum_both = sum_value * sum_weight

def avg():
    average = sum_both / sum_weight
    return average
avg()

24.0

Q 339.Write a python function to find Roots of a Linear Equation, Find all values of x that solve 4x - 8 = 0 from a list.

In [10]:
m = [2,3,6,5,4,7,8,9,5,4,7,8]
def roots(x):
    s = (4 * x) - 8
    if s == 0:
        return x
m_result = list(filter(roots,m))
print(m_result)

[2]


Q 340.Write a python function to find Running Sum (Cumulative Sum) for a list of numbers.

In [12]:
from functools import reduce
numbers = [1, 2, 3, 4, 5]
def sum_func(a, x):
    total, result = a
    total += x
    result += [total]
    return total, result
total, result = reduce(sum_func, numbers, (0, []))
print(result)

[1, 3, 6, 10, 15]


Q 341. Write a python function to Count How Many Numbers Are Above the Mean. Take a list of numbers and calculate the mean first then find the numbers greater than the mean.

In [13]:
from functools import reduce
numbers = [10,20,11,40,50]

def count_elements(n):
    count = 0
    for n in numbers:
        count += 1
    return count
total = reduce(lambda x, y: x + y, numbers)
avg = total // count_elements(numbers)
print(avg)
def mean(numbers):
    greater = []
    for num in numbers:
        if num > avg:
            greater = greater + [num]
            
    return greater

result = list(mean(numbers))
print(result)


        


26
[40, 50]
